;/*FB_PKG_DELIM*/

__d("HelpCenterAISearchPageEntryPointRootQuery$Parameters",["cr:2221"],(function(t,n,r,o,a,i,l){"use strict";i.exports=n("cr:2221")}),34);
__d("HelpCenterAISearchPage.entrypoint",["HelpCenterAISearchPageEntryPointRootQuery$Parameters","JSResourceForInteraction"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.helpIdentifier,n=t.query,o=t.regionHint;return{queries:{searchQueryReference:{parameters:r("HelpCenterAISearchPageEntryPointRootQuery$Parameters"),variables:{helpIdentifier:e,query:n,regionHint:o}}}}},root:r("JSResourceForInteraction")("HelpCenterAISearchPageEntryPointRoot.react").__setRef("HelpCenterAISearchPage.entrypoint")},s=e;l.default=s}),98);
__d("HelpCenterNavigationPageRootQuery$Parameters",["cr:4046"],(function(t,n,r,o,a,i,l){"use strict";i.exports=n("cr:4046")}),34);
__d("HelpCenterNavigationPageRoot.entrypoint",["HelpCenterNavigationPageRootQuery$Parameters","JSResourceForInteraction"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.routeProps.identifier;return{queries:{HelpCenterNavigationPageRootQueryReference:{parameters:r("HelpCenterNavigationPageRootQuery$Parameters"),variables:{helpIdentifier:e}}}}},root:r("JSResourceForInteraction")("HelpCenterNavigationPageRoot.react").__setRef("HelpCenterNavigationPageRoot.entrypoint")},s=e;l.default=s}),98);
__d("HelpCenterSearchPageRootQuery$Parameters",["cr:489"],(function(t,n,r,o,a,i,l){"use strict";i.exports=n("cr:489")}),34);
__d("HelpCenterTraditionalSearchPageRootQuery$Parameters",["cr:3015"],(function(t,n,r,o,a,i,l){"use strict";i.exports=n("cr:3015")}),34);
__d("MetaSupportAssistantQuerySummaryQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="37284928194488096"}),null);
__d("MetaSupportAssistantQuerySummaryQuery$Parameters",["MetaSupportAssistantQuerySummaryQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("MetaSupportAssistantQuerySummaryQuery_facebookRelayOperation"),metadata:{},name:"MetaSupportAssistantQuerySummaryQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("MetaSupportAssistantQuerySummaryRoot.entrypoint",["JSResourceForInteraction","MetaSupportAssistantQuerySummaryQuery$Parameters"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.clientRequestId,n=t.helpIdentifier,o=t.query;return{extraProps:{helpIdentifier:n,userQuery:o},queries:{queryRef:{parameters:r("MetaSupportAssistantQuerySummaryQuery$Parameters"),variables:{input:{client_request_id:e,help_identifier:n,query:o}}}}}},root:r("JSResourceForInteraction")("MetaSupportAssistantQuerySummaryRoot.react").__setRef("MetaSupportAssistantQuerySummaryRoot.entrypoint")};l.default=e}),98);
__d("HelpCenterTraditionalSearchPage.entrypoint",["HelpCenterMaisaCommonRolloutClientGate.entrypointutils","HelpCenterTraditionalSearchPageRootQuery$Parameters","JSResourceForInteraction","MetaSupportAssistantQuerySummaryRoot.entrypoint","NestedRelayEntryPointBuilderUtils"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.helpIdentifier,a=t.maisa_request_id,i=t.query,l=t.regionHint,s=!0;return e==="FACEBOOK"?s=o("HelpCenterMaisaCommonRolloutClientGate.entrypointutils").getIsFacebookHelpCenterCommonRolloutAllowedEntrypoint(e):e==="MESSENGER"?s=o("HelpCenterMaisaCommonRolloutClientGate.entrypointutils").getIsMessengerHelpCenterCommonRolloutAllowedEntrypoint(e):e==="INSTAGRAM"&&(s=o("HelpCenterMaisaCommonRolloutClientGate.entrypointutils").getIsInstagramHelpCenterCommonRolloutAllowedEntrypoint(e)),{entryPoints:{metaSupportAssistantEntryPoint:s?o("NestedRelayEntryPointBuilderUtils").NestedRelayEntryPoint({entryPoint:n("MetaSupportAssistantQuerySummaryRoot.entrypoint"),entryPointParams:{clientRequestId:a,helpIdentifier:e,query:i!=null?i:""}}):void 0},queries:{searchQueryReference:{parameters:r("HelpCenterTraditionalSearchPageRootQuery$Parameters"),variables:{helpIdentifier:e,query:i,regionHint:l}}}}},root:r("JSResourceForInteraction")("HelpCenterTraditionalSearchPageRoot.react").__setRef("HelpCenterTraditionalSearchPage.entrypoint")},s=e;l.default=s}),98);
__d("HelpCenterSearchPageRoot.entrypoint",["HelpCenterAISearchPage.entrypoint","HelpCenterEntryPointUtils.entrypointutils","HelpCenterSearchPageRootQuery$Parameters","HelpCenterTraditionalSearchPage.entrypoint","JSResourceForInteraction","NestedRelayEntryPointBuilderUtils"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.routeParams,a=e.maisa_request_id,i=e.q,l=e.query,s=e.region_hint,u=t.routeProps.identifier,c=l!=null?l:i,d=o("HelpCenterEntryPointUtils.entrypointutils").getRegionHintsEnum(s),m=o("HelpCenterEntryPointUtils.entrypointutils").getShouldShowAIModeSearchEntrypoint(u);return{entryPoints:{searchPageContentEntryPoint:o("NestedRelayEntryPointBuilderUtils").NestedRelayEntryPoint({entryPoint:n(m?"HelpCenterAISearchPage.entrypoint":"HelpCenterTraditionalSearchPage.entrypoint"),entryPointParams:{helpIdentifier:u,maisa_request_id:a,query:c,regionHint:d}})},extraProps:{isAIMode:m},queries:{HelpCenterSearchPageRootQueryReference:{parameters:r("HelpCenterSearchPageRootQuery$Parameters"),variables:{helpIdentifier:u}}}}},root:r("JSResourceForInteraction")("HelpCenterSearchPageRoot.react").__setRef("HelpCenterSearchPageRoot.entrypoint")},s=e;l.default=s}),98);
__d("HelpCenterSearchPageRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="28192357440385798"}),null);
__d("HelpCenterSearchPageRootQuery_instagramRelayOperation",[],(function(t,n,r,o,a,i){a.exports="28192357440385798"}),null);
__d("HelpCenterTraditionalSearchPageRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="26717462507892526"}),null);
__d("HelpCenterTraditionalSearchPageRootQuery_instagramRelayOperation",[],(function(t,n,r,o,a,i){a.exports="26717462507892526"}),null);