(function(c){var a=window.AmazonUIPageJS||window.P,d=a._namespace||a.attributeErrors,b=d?d("InternationalCustomerPreferencesNavAssets",""):a;b.guardFatal?b.guardFatal(c)(b,window):b.execute(function(){c(b,window)})})(function(c,a,d){a.$Nav&&(new MutationObserver(function(b,c){a.google&&a.google.translate&&(ue&&ue.count("googleTranslation",1),c.disconnect())})).observe(document,{attributes:!0,childList:!0,subtree:!0})});
/* ******** */
(function(k){var d=window.AmazonUIPageJS||window.P,l=d._namespace||d.attributeErrors,p=l?l("InternationalCustomerPreferencesNavDesktopAssets",""):d;p.guardFatal?p.guardFatal(k)(p,window):p.execute(function(){k(p,window)})})(function(k,d,l){d.$Nav&&d.$Nav.when("$").run("icp.main",function(a){function c(c,e){if(c=a(e).attr("href"))c=c.replace("preferencesReturnUrl\x3d%2F","preferencesReturnUrl\x3d"+b),a(e).attr("href",c)}var b=encodeURIComponent(d.location.pathname+d.location.search);a("#icp-nav-dialog, #icp-nav-flyout").each(c);
a("#icp-touch-link-language, #icp-touch-link-country, #icp-touch-link-cop").each(c);a("*[id*\x3dicp-flyout-mkt-change]").each(c);d.$Nav.when("$","page.loaded").run("icp.latency_exp",function(a){if(a("#icp-country-button-experiment").length){var c=a("#icp-country-button-experiment").html(),d=a("#icp-country-button-experiment-url").html();d=d.replace("preferencesReturnUrl\x3d%2F","preferencesReturnUrl\x3d"+b);c='\x3ca href\x3d"'+d+'" class\x3d"icp-button a-declarative" id\x3d"icp-touch-link-country"\x3e \x3cspan class\x3d"icp-flag-3 icp-flag-3-jp"\x3e\x3c/span\x3e\x3cspan class\x3d"icp-color-base"\x3e'+
c+"\x3c/span\x3e \x3c/a\x3e";a("#icp-country-button-experiment").replaceWith(a(c));a("#icp-country-button-experiment-url").remove()}})});k={flyoutDataEndpoint:"/customer-preferences/api/flyout/xop-and-country",saveSettingsEndpoint:"/customer-preferences/api/xop"};var p={};"use strict";d.$Nav&&(d.$Nav.when("$","data","flyouts.create","flyouts.accessibility","flyout.icp.language.endpointConfig","flyout.icp.language.saveLanguageAndReloadPage","flyout.icp.currency.saveCurrencyAndReloadPage","flyout.icp.weblabConfig",
"flyout.icp.aapi.saveLanguageAndReload","flyout.icp.aapi.saveCurrencyAndReload").build("flyout.icp.language.builder",function(a,c,b,f,e,k,p,n,v,w){function A(a,c){a=a.elem().find('a[href*\x3d"#switch-'+c+'"]');c=a.first().nextUntil(a.last(),".nav-divider");var b=a.add(c);a.wrap("\x3cli\x3e\x3c/li\x3e");c.wrap("\x3cli aria-hidden\x3d'true'\x3e\x3c/li\x3e");b.parent().wrapAll('\x3cul role\x3d"list"\x3e\x3c/ul\x3e');return b}var B=e||{},t=function(){return{extractLanguage:function(a){var c=(a||"").indexOf("#switch-lang\x3d");
return-1===c?"":a.substr(c+13)},insertLanguage:function(a){return"#switch-lang\x3d"+a},extractCurrency:function(a){var c=(a||"").indexOf("#switch-currency\x3d");return-1===c?"":a.substr(c+17)},insertCurrency:function(a){return"#switch-currency\x3d"+a}}}(),x=function(a){var c=a.current?'\x3ci class\x3d"icp-radio icp-radio-active"\x3e\x3c/i\x3e':'\x3ci class\x3d"icp-radio"\x3e\x3c/i\x3e',b=t.insertCurrency(a.code);return{text:c+a.name,url:b}},y,z,u=function(a,b){var e=a||{},h=e.languages,f=e.currency;
a=e.inputs||{};var n=e.accessibility||{},q=[],g=e.currentAndPopularCurrencies,k=g!==l;if(h!==l&&h.all!==l&&1<h.all.length){var m=h.strings;if(m){var r='\x3cspan role\x3d"heading" aria-level\x3d"6"\x3e'+m.changeText+"\x3c/span\x3e";k?q.push({text:r}):q.push({text:r+(m.helpLinkText?' \x3ca href\x3d"'+m.helpLinkHref+'" class\x3d"icp-flyout-learn-more" aria-label\x3d"'+m.helpLinkAriaText+'"\x3e'+m.helpLinkText+"\x3c/a\x3e":"")})}for(m=0;m<h.all.length;m++){r=h.all[m];var F=r.current?'\x3ci class\x3d"icp-radio icp-radio-active"\x3e\x3c/i\x3e':
'\x3ci class\x3d"icp-radio"\x3e\x3c/i\x3e',G=t.insertLanguage(r.code);r={text:F+r.name,url:G};1===m&&(r.dividerBefore=!h.localeDividerHidden,z=!0);q.push(r)}}if(e.cop)if(m=h!==l&&h.all!==l&&1<h.all.length,k&&g!==l&&g.currencyList!==l&&1<g.currencyList.length){if(g.strings){q.push({text:'\x3cspan role\x3d"heading" aria-level\x3d"6"\x3e'+g.strings.changeText+"\x3c/span\x3e",dividerBefore:m});for(f=0;f<g.currencyList.length;f++)q.push(x(g.currencyList[f]));q.push({text:'\x3ca href\x3d"'+g.strings.editPageHref+
'" aria-label\x3d"'+g.strings.seeAllText+'"\x3e'+g.strings.seeAllText+"\x3c/a\x3e"})}}else f&&f.strings&&(g=f.strings,q.push({text:'\x3cspan role\x3d"heading" aria-level\x3d"6"\x3e'+g.changeText+"\x3c/span\x3e"+(g.helpLinkText?' \x3ca href\x3d"'+g.helpLinkHref+'" class\x3d"icp-flyout-learn-more" aria-label\x3d"'+g.helpLinkAriaText+'"\x3e'+g.helpLinkText+"\x3c/a\x3e":""),dividerBefore:m}),f="\x3cspan\x3e"+g.currencyName+"\x3c/span\x3e",k=encodeURIComponent(d.location.pathname+d.location.search),f+=
'\x3ca href\x3d"'+g.changeHref.replace("%s",k)+'" class\x3d"icp-flyout-change"\x3e'+g.changeShortText+"\x3c/a\x3e",q.push({text:f}));e.marketplace&&(g=e.marketplace,f=g.strings,g.country&&f.text&&(q.push({text:'\x3ci class\x3d"icp-flyout-flag icp-flyout-flag-'+g.country+'"\x3e\x3c/i\x3e'+f.text,dividerBefore:h!==l||e.cop&&e.currency!==l}),g.href&&f.link&&q.push({text:'\x3cdiv class\x3d"icp-mkt-change-lnk"\x3e'+f.link+"\x3c/div\x3e",url:g.href,id:"icp-flyout-mkt-change"})));n&&n.flyoutAriaLabel&&(y=
n.flyoutAriaLabel);e={};e[b]={template:{name:"itemList",data:{items:q,inputs:a}}};c(e)};return function(e){e=e||{};var f=e.convertedInlineData,d=e.name+"Content";f?u(f,d):c.observe("data",function(a){u(a,d)});var h=b({key:e.name,panelDataKey:d,link:e.target,event:"icp",arrow:"top",cover:e.isCoverEnabled});h.a11ysetup=function(){if(!opts.suspendTabbing){var c=a(h.elem().find(".nav-flyout-content").find(".nav-link,\x3ea,.icp-flyout-learn-more,.icp-flyout-change"));0<c.length?h.a11y.elems(c):h.a11y.elems(a(h.elem().find("a")))}};
h.getPanel().onData(function(c){y&&h.elem().attr("aria-label",y);var b=h.elem().find(".nav-divider"),d=z?1:0;if(b.length>1+d)for(;d<=b.length;d++){var g=b.eq(d);g.addClass("icp-flyout-curr-divider")}if(!e.isHeader)for(b=h.elem().find(".nav-divider"),d=z?1:0;d<b.length;d++)g=b.eq(d),g.hide(),g.nextAll().hide();var n=e.isHeader?"tn":"fo";A(h,"lang");A(h,"currency");h.elem().find('a[href*\x3d"#switch-lang"]').each(function(b,e){var d=a(e);b=t.extractLanguage(d.attr("href"));d.attr("lang",b.replace("_",
"-"));0<d.find("span:has(i.icp-radio-active)").length&&d.attr("aria-current","true");d.click(function(b){b.preventDefault();b=t.extractLanguage(d.attr("href"));if(f&&f.aapi)v(f.aapi,b);else{var e="icp_lop_"+b.replace("_","-")+"_"+n;k(a,B.saveSettingsEndpoint+"?ref_\x3d"+e,b,c.template.data.inputs.token)}})});h.elem().find('a[href*\x3d"#switch-currency"]').each(function(b,e){var d=a(e);b=t.extractCurrency(d.attr("href"));d.attr("currency",b);0<d.find("span:has(i.icp-radio-active)").length&&d.attr("aria-current",
"true");d.click(function(b){b.preventDefault();b=t.extractCurrency(d.attr("href"));f&&f.aapi?w(f.aapi,b):p(a,B.saveSettingsEndpoint+"?ref_\x3d"+("icp_cop_"+b+"_"+n),b,c.template.data.inputs.token)})})});return h}}),d.$Nav.when("provider.ajax","util.Proximity","flyout.icp.language.endpointConfig").build("flyout.icp.language.ajax",function(a,c,b){var d=a({url:b&&b.flyoutDataEndpoint,data:{icpContent:"icp"}}).boundFetch();return function(a){a.onShow(d);a.link.focus(d);a.link.find("button").first().focus(d);
c.onEnter(a.link,[20,40,40,40],d)}}),d.$Nav.declare&&(d.$Nav.declare("flyout.icp.language.endpointConfig",k),d.$Nav.declare("flyout.icp.weblabConfig",p)));"use strict";if(d.$Nav){var H=/^[A-Z]{3}$/,v=function(a){return'\x3cspan style\x3d"unicode-bidi:isolate; direction:ltr;" dir\x3d"ltr"\x3e'+a+"\x3c/span\x3e"},w=function(a){try{return a()}catch(c){return l}},I=function(a,c){return w(function(){var b=(new Intl.NumberFormat(c,{style:"currency",currency:a})).formatToParts(0).filter(function(a){return"currency"===
a.type})[0];return b&&b.value})},J=function(a,c){return w(function(){var b=(new Intl.DisplayNames([c],{type:"currency"})).of(a);return b===a?l:b})},K=function(a){return(a=(a&&a.languageDetails||[]).filter(function(a){return a.isCurrent})[0])&&a.code||document.documentElement.lang||"en-US"},L=function(a,c){var b=a.popularCurrencies,d=function(a){return H.test(a.code)};return b&&b.currencyList.every(d)?{currencyList:b.currencyList.map(function(b){var d=b.code,e=b.current,f;(f=b.current&&a.formattedDisplayNameWithSymbol)||
(b=b.code,f=I(b,c),f=[f&&f!==b&&v(f),v(b),J(b,c)].filter(Boolean).join(" - "));return{code:d,current:e,name:f}}),strings:b.strings}:l},x=function(a){return{all:a.languageDetails.map(function(a){return{current:a.isCurrent,name:a.formattedDisplayNameAndCode,code:a.code}}),strings:{helpLinkHref:a.helpLinkHref,helpLinkText:a.helpLinkText,helpLinkAriaText:a.helpLinkAriaText,changeText:a.changeText},localeDividerHidden:a.isLocaleDividerHidden}};k=function(a,c,b){d.$Nav.when("$","flyout.icp.language.builder",
"flyout.icp.language.ajax","config","page.loaded").run("flyout.icp.language."+a,function(f,e,k,p,n){f=f(b.selector);b.isPresent(f)&&(n=(n=d.$Nav.getNow("flyout.icp."+a+".data",null))?c(n):null,e=e({name:b.name,target:f,isHeader:b.isHeader,isCoverEnabled:b.isHeader?!p.primeDay:l,convertedInlineData:n}),n||k(e))})};k("header",function(a){var c=a.currencyInfo;return{languages:x(a.languageInfo),cop:c.copEnabled,currency:{code:c.code,strings:{changeHref:c.changeHref,changeShortText:c.changeShortText,changeText:c.changeText,
helpLinkText:c.helpLinkText,helpLinkAriaText:c.helpLinkAriaText,helpLinkHref:c.helpLinkHref,currencyName:c.formattedDisplayNameWithSymbol}},currentAndPopularCurrencies:L(c,K(a.languageInfo)),marketplace:{country:a.marketplaceInfo.countryCode,href:a.marketplaceInfo.href,strings:{text:a.marketplaceInfo.text,link:a.marketplaceInfo.linkText}},inputs:{token:a.aapi.csrfToken},aapi:a.aapi}},{selector:"#icp-nav-flyout",name:"icp",isHeader:!0,isPresent:function(a){return 1===a.length}});k("footer",function(a){return{languages:x(a.languageInfo),
inputs:{token:a.aapi.csrfToken},aapi:a.aapi}},{selector:"#icp-touch-link-language",name:"icp-footer-flyout",isHeader:!1,isPresent:function(a){return 1===a.find(".icp-up-down-arrow").length}})}if(d.$Nav.declare){var u=function(a,c){var b=new URLSearchParams(d.location.search);b.set(a,c);d.location.search=b.toString()};d.$Nav.declare("flyout.icp.language.saveLanguageAndReloadPage",function(a,c,b,d){C(a,c,d,{lop:b},"language")});d.$Nav.declare("flyout.icp.currency.saveCurrencyAndReloadPage",function(a,
c,b,d){C(a,c,d,{cop:b},"currency")});var C=function(a,c,b,d,e){a.ajax({url:c,type:"POST",contentType:"application/json; charset\x3dUTF-8",data:JSON.stringify(d),headers:{"anti-csrftoken-a2z":b},success:function(){u(e,Object.values(d)[0])}})};d.$Nav.declare("flyout.icp.aapi.saveLanguageAndReload",function(a,c){D(a,"language",c)});d.$Nav.declare("flyout.icp.aapi.saveCurrencyAndReload",function(a,c){D(a,"currency",c)});var E=function(a,c){if("currency"===a&&/^[A-Z]{3}$/.test(c)){var b=d.location.hostname;
b=0===b.indexOf("www.")?b.substring(3):"."+b;document.cookie="i18n-prefs\x3d"+c+"; domain\x3d"+b+"; path\x3d/; max-age\x3d31536000"}u(a,c)},D=function(a,c,b){if(d.$Nav.getNow("config.isRecognized")){var f=(document.querySelector('meta[name\x3d"encrypted-slate-token"]')||{}).content||"",e="https://"+a.domain+"/api/marketplaces/"+a.marketplaceId+"/customer/i18n-preferences/"+c,k={};k[c]=b;fetch(e,{method:"POST",headers:{Accept:'application/vnd.com.amazon.api+json; type\x3d"customer.i18n-preferences.set-'+
c+'/v1"',"Content-Type":'application/vnd.com.amazon.api+json; type\x3d"customer.i18n-preferences.set-'+c+'.request/v1"',"x-api-csrf-token":a.csrfToken,"x-amzn-encrypted-slate-token":f},credentials:"include",body:JSON.stringify(k)}).then(function(a){a.ok&&E(c,b)}).catch(function(){})}else E(c,b)}}});
/* ******** */
