'use strict';(function(e){var g=window.AmazonUIPageJS||window.P,h=g._namespace||g.attributeErrors,c=h?h("DetailPageRipersAssets",""):g;c.guardFatal?c.guardFatal(e)(c,window):c.execute(function(){e(c,window)})})(function(e,g,h){e.when("afterLoad").register("ripers-device-utils",function(){return{getDeviceType:function(){return"Desktop"}}});"use strict";e.when("ripers-device-utils").register("ripers-metrics",function(c){var f=g.ue,a="object"===typeof f&&f.count,e="RipersBadge:"+c.getDeviceType()+":";
return{recordClick:function(d){"object"===typeof d&&null!==d&&h!==d.counter&&(d=d.counter)&&a&&f.count(e+d,1)},recordTiming:function(d){if("object"===typeof d&&null!==d&&h!==d.timer){var c=d.timer;d=d.durationMs;c&&a&&"number"===typeof d&&isFinite(d)&&0<=d&&f.count(e+c,Math.round(d))}}}});"use strict";e.declare("ripers-buybox-config",{selectors:{buyboxTabSet:"#offerDisplayGroupTabSet",buyboxAccordionRows:"#buyBoxAccordion",ripersBadges:"#buyingOptionRipersBadge_feature_div \x3e div, #buyingOptionRipersInlineBadge_feature_div \x3e div"},
tabs:{tab_desktop_buybox_group_1:"#tab_heading_desktop_buybox_group_1",tab_desktop_buybox_group_2:"#tab_heading_desktop_buybox_group_2",tab_mobile_buybox_group_1:"#tab_heading_mobile_buybox_group_1",tab_mobile_buybox_group_2:"#tab_heading_mobile_buybox_group_2",tab_mobileapp_buybox_group_1:"#tab_heading_mobileapp_buybox_group_1",tab_mobileapp_buybox_group_2:"#tab_heading_mobileapp_buybox_group_2"},accordionRowsToRipers:{newAccordionRow:["NEW_1_ripers_badge","NEW_1_ripers_inline_badge"],SecondNewAccordionRow:["NEW_2_ripers_badge",
"NEW_2_ripers_inline_badge"]},ripersToAccordionRows:{NEW_1_ripers_badge:["newAccordionRow_0","newAccordionRow_1","newAccordionRow_2","newAccordionRow_3"],NEW_1_ripers_inline_badge:["newAccordionRow_0","newAccordionRow_1","newAccordionRow_2","newAccordionRow_3"],NEW_2_ripers_badge:["newAccordionRow_1","newAccordionRow_2","newAccordionRow_3","newAccordionRow_4"],NEW_2_ripers_inline_badge:["newAccordionRow_1","newAccordionRow_2","newAccordionRow_3","newAccordionRow_4"]},ripersToSingleOffer:{NEW_1_ripers_badge:["qualifiedBuybox_globalMatchbox_3",
"qualifiedBuybox_globalMatchbox_2","qualifiedBuybox_globalMatchbox_1","qualifiedBuybox"],NEW_1_ripers_inline_badge:["qualifiedBuybox_globalMatchbox_3","qualifiedBuybox_globalMatchbox_2","qualifiedBuybox_globalMatchbox_1","qualifiedBuybox"]}});"use strict";e.when("A","ripers-buybox-config","atf").register("ripers-buying-option-controller",function(c,f){var a=g.performance&&g.performance.now?g.performance.now():null,l=c.$,d,r,k,m,t=function(){for(var b=document.querySelectorAll(f.selectors.ripersBadges),
d=[],c=0;c<b.length;c++){var a=b[c];a.id&&d.push(a.id)}return d},u=function(){d=0<l(f.selectors.buyboxTabSet).length;r=0<l(f.selectors.buyboxAccordionRows).length;k=t();if(d)a:{for(var b in f.tabs)if(l(f.tabs[b]).hasClass("a-active")){m=b;break a}m=h}},n=function(){k=t();for(var b=0;b<k.length;b++){var d=document.getElementById(k[b]);d&&d.classList.add("aok-hidden")}},v=function(b){b=f.ripersToSingleOffer[b];if(b!==h)for(var c=0;c<b.length;c++){var a=document.getElementById(b[c]);if(a)if(d){var e=
document.getElementById(m);if(null!==e&&e.contains(a))return!0}else return!0}return!1},p=function(b){(b=document.getElementById(b))&&b.classList.remove("aok-hidden")},q=function(){for(var b=0;b<k.length;b++){var c=k[b];if(r){a:{var a=f.ripersToAccordionRows[c];if(a!==h)for(var e=0;e<a.length;e++){var g=document.getElementById(a[e]);if(g&&g.classList.contains("a-accordion-active"))if(d){var l=document.getElementById(m);if(null!==l&&l.contains(g)){a=!0;break a}}else{a=!0;break a}}a=!1}if(a||v(c)){p(k[b]);
break}}else if(v(c)){p(k[b]);break}}};document.querySelector(f.selectors.ripersBadges)&&(u(),q());(function(){c.on("a:tabs:offerDisplayGroup_tabs:select",function(b){n();m=b.selectedTab.tabName;q()})})();(function(){c.on("a:accordion:buybox-accordion:select",function(b){n();if(b=f.accordionRowsToRipers[b.selectedRow.rowName])for(var a=0;a<b.length;a++)p(b[a])})})();(function(){c.on("a:pageUpdate",function(){n();u();q()})})();if(null!==a){var w=g.performance.now()-a;e.when("ripers-metrics").execute(function(a){a.recordTiming({timer:"Controller:ExecMs",
durationMs:w})})}});"use strict";e.when("A").execute(function(c){var f=null;e.when("rufus-handle-stream").execute(function(a){var g=c.$("#hrr-rufus-similar-products-link-desktop");a&&g.length&&(f=a,g.removeClass("aok-hidden"),e.when("ripers-metrics").execute(function(a){a.recordClick({counter:"RufusDeeplink:Revealed"})}))});c.declarative("a-hrr-rufus-deeplink-desktop","click",function(a){a.$event.preventDefault();a=(a=document.getElementById("hrr-rufus-similar-products-link-desktop"))&&a.textContent?
a.textContent.trim():"Similar items customers keep";f&&f({qis:"NileDPHRRABadgeIngress",query:a,metricName:"HRRABadgeRufusIngressDesktop"})});e.when("ripers-metrics").execute(function(a){a.recordClick({counter:"RufusDeeplink:AssetsLoaded"})})})});