'use strict';(function(d){var n=window.AmazonUIPageJS||window.P,m=n._namespace||n.attributeErrors,f=m?m("CentaurusUIMarkupAssets@CentaurusUIWlpInjectableAssets","CentaurusUIMarkupAssets"):n;f.guardFatal?f.guardFatal(d)(f,window):f.execute(function(){d(f,window)})})(function(d,n,m){(function(){var f=function(b,k,a,h){return new (a||(a=Promise))(function(e,c){function d(a){try{f(h.next(a))}catch(l){c(l)}}function g(a){try{f(h.throw(a))}catch(l){c(l)}}function f(c){var l;c.done?e(c.value):(l=c.value,
l instanceof a?l:new a(function(a){a(l)})).then(d,g)}f((h=h.apply(b,k||[])).next())})},m=function(b,k){function a(a){return function(f){return function(a){if(h)throw new TypeError("Generator is already executing.");for(;d&&(d=0,a[0]&&(g=0)),g;)try{if(h=1,e&&(c=2&a[0]?e.return:a[0]?e.throw||((c=e.return)&&c.call(e),0):e.next)&&!(c=c.call(e,a[1])).done)return c;switch(e=0,c&&(a=[2&a[0],c.value]),a[0]){case 0:case 1:c=a;break;case 4:return g.label++,{value:a[1],done:!1};case 5:g.label++;e=a[1];a=[0];
continue;case 7:a=g.ops.pop();g.trys.pop();continue;default:if(!((c=0<(c=g.trys).length&&c[c.length-1])||6!==a[0]&&2!==a[0])){g=0;continue}if(3===a[0]&&(!c||a[1]>c[0]&&a[1]<c[3]))g.label=a[1];else if(6===a[0]&&g.label<c[1])g.label=c[1],c=a;else if(c&&g.label<c[2])g.label=c[2],g.ops.push(a);else{c[2]&&g.ops.pop();g.trys.pop();continue}}a=k.call(b,g)}catch(p){a=[6,p],e=0}finally{h=c=0}if(5&a[0])throw a[1];return{value:a[0]?a[1]:void 0,done:!0}}([a,f])}}var h,e,c,d,g={label:0,sent:function(){if(1&c[0])throw c[1];
return c[1]},trys:[],ops:[]};return d={next:a(0),throw:a(1),return:a(2)},"function"==typeof Symbol&&(d[Symbol.iterator]=function(){return this}),d},q=function(){function b(b,a){this.A=b;this.marsCsaLogger=this.api=null;this.loadScript(a);this.initMarsCsaLogger();this.registerWlpActionEventHandler()}return b.getInstance=function(k,a){return b.instance||(b.instance=new b(k,a)),b.instance},b.prototype.registerWlpActionEventHandler=function(){var k=this;this.A.declarative(b.WLP_ACTION_EVENT,"click",function(a){var h,
e=null===(h=document.getElementById(a.data.elementId))||void 0===h?void 0:h.getAttribute(b.WLP_ATTR_ID);if(e){try{k.sendMetric(a.data.metricId,a.data.producerId)}catch(c){d.log("Failed to send metric: ".concat(c),"ERROR")}k.showExperience(e)}else d.log("Unable to retrieve wlp id","ERROR")})},b.prototype.initMarsCsaLogger=function(){var b=this;d.now("marsCsaLogger").execute("marsCsaLogger-safe-register",function(a){if(a)return d.log("marsCsaLogger has already been registered","WARN"),void(b.marsCsaLogger=
a);d.when("marsCsaLogger").execute(function(a){b.marsCsaLogger=a})})},b.prototype.sendMetric=function(b,a){this.marsCsaLogger?this.marsCsaLogger.send(b,a):d.log("marsCsaLogger not initialized, metric dropped","WARN")},b.prototype.loadScript=function(d){if(!document.getElementById(b.SCRIPT_ID)){var a=document.createElement("script");a.id=b.SCRIPT_ID;a.defer=!0;a.src=d;document.head.appendChild(a)}},b.prototype.initExperience=function(k,a){return f(this,void 0,void 0,function(){var h,e,c;return m(this,
function(f){switch(f.label){case 0:return[4,this.getAPI()];case 1:return h=f.sent(),e=h.initiate(a,{}),(c=document.getElementById(k))?(c.setAttribute(b.WLP_ATTR_ID,e),this.checkAndLoadFromQueryParam(a.clientId,a.ingressId,e)):d.log("Unable to set wlp id on element","ERROR"),[2]}})})},b.prototype.showExperience=function(b){return f(this,void 0,void 0,function(){return m(this,function(a){switch(a.label){case 0:return[4,this.getAPI()];case 1:return[2,a.sent().show(b)]}})})},b.prototype.checkAndLoadFromQueryParam=
function(b,a,h){var e=(new URLSearchParams(n.location.search)).get("loadInjectable");if(e){var c=e.split("_");if(2!==c.length)return void d.log("Invalid loadInjectable format: expected 'clientId_ingressId', got '".concat(e,"'"),"WARN");e=c[1];c[0]===b&&e===a&&this.showExperience(h).catch(function(a){d.log("Failed to show experience from query param: ".concat(a),"ERROR")})}},b.prototype.getAPI=function(){return f(this,void 0,void 0,function(){var f=this;return m(this,function(a){return this.api?[2,
Promise.resolve(this.api)]:[2,new Promise(function(a){d.when(b.MODULE_NAME).execute(function(b){f.api=b;a(b)})})]})})},b.SCRIPT_ID="wlp-injectable-script",b.MODULE_NAME="sfx-injectable",b.WLP_ACTION_EVENT="cui-wlp-action-event",b.WLP_ATTR_ID="data-wlp-id",b.instance=null,b}();d.now("centaurus-ui-wlp-manager-module").execute("centaurus-ui-wlp-manager-module-safe-register",function(b){if(b)d.log("centaurus-ui-wlp-manager-module has already been registered","WARN");else try{d.when("A","ready").register("centaurus-ui-wlp-manager",
function(b){var a;return{getInstance:function(d){return a||(a=q.getInstance(b,d)),a}}})}catch(k){d.log("centaurus-ui-wlp-injectable-module registration experienced an issue "+k,"ERROR")}})})()});