'use strict';mix_d("AmazonHaulSolitareCards__haul-cx-hero-carousel:haul-cx-hero-carousel__-Jr2tx6E","exports tslib @c/scoped-dom @c/dom @c/aui-carousel @c/aui-utils".split(" "),function(r,t,z,A,B,C){function u(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var m=u(z),q=u(A),D=u(B),x=function(a){var d=!!a.dataset.carouselEnabled;a=Number(a.dataset.rotationTime||0);return{carouselEnabled:d,rotationTime:a,shouldEnableCarousel:d&&0<a}},E=function(){var a,d,b=null===(a=q["default"].cardRoot)||
void 0===a?void 0:a.ownerDocument;a=null===b||void 0===b?void 0:b.defaultView;return null===(d=null===a||void 0===a?void 0:a.matchMedia)||void 0===d?void 0:d.call(a,"(prefers-reduced-motion: reduce)")},F=function(a,d,b){void 0===b&&(b=5E3);var c=null,f=null,h=!1;return{start:function(){var k=this;c||(c=C.interval(function(){h=!0;a.gotoNextPage()},d||3E3),0<b&&null===f&&(f=setTimeout(function(){return k.stop()},b)))},stop:function(){c&&(clearInterval(c),c=null);null!==f&&(clearTimeout(f),f=null)},
isAutoUpdate:function(){return h},resetAutoFlag:function(){h=!1}}},H=function(a){var d=a.startFrozen,b=a.root,c=m["default"].cardRoot.querySelector("[data-pause-btn]"),f=function(){var e,g=null===(e=b.querySelectorAll)||void 0===e?void 0:e.call(b,"img");return g?Array.from(g):[]},h=function(){return f().some(function(e){return!!e.dataset.originalSrc})},k=function(e){var g,v,w;e?null===(g=b.setAttribute)||void 0===g?void 0:g.call(b,"data-current-is-gif",""):null===(v=b.removeAttribute)||void 0===v?
void 0:v.call(b,"data-current-is-gif");null===(w=null===c||void 0===c?void 0:c.toggleAttribute)||void 0===w?void 0:w.call(c,"inert",!e)},l=(b.dataset.gifPages||"").split(",").map(function(e){return"1"===e}),n=function(e){void 0===e&&(e=h());c&&(c.setAttribute("data-paused",String(e)),c.setAttribute("aria-label",e?c.dataset.labelPlay||"Play animation":c.dataset.labelPause||"Pause animation"))};a=function(){var e=f();e.some(function(g){return!!g.dataset.originalSrc})?e.forEach(G):e.forEach(y);e=e.some(function(g){return!!g.dataset.originalSrc});
n(e)};var p=function(){f().forEach(y);n()};k(!0===l[0]);d?p():n();null===c||void 0===c?void 0:c.addEventListener("click",a);return{freezeAll:p,onSlideChange:function(e){k(!0===l[e-1])}}},y=function(a){var d=a.src||a.getAttribute("src")||"";var b=d?d.toLowerCase().startsWith("https://m.media-amazon.com/")?d.split("?")[0].toLowerCase().endsWith(".gif"):!1:!1;if(b&&!a.dataset.originalSrc){b=a.closest("picture");b=null===b||void 0===b?void 0:b.querySelector('source[media*="reduced-motion"]');var c;if(!(c=
null===b||void 0===b?void 0:b.getAttribute("srcset")))a:{if(d&&d.toLowerCase().startsWith("https://m.media-amazon.com/")){var f=t.__read(d.split("?"));c=f[0];f=f.slice(1);if(c.toLowerCase().endsWith(".gif")){c=c.slice(0,-4);f=0<f.length?"?"+f.join("?"):"";c=c+"._FMpng_.gif"+f;break a}}c=void 0}c&&(a.dataset.originalSrc=d,a.src=c,b&&(b.media="not all"))}},G=function(a){a.dataset.originalSrc&&(a.src=a.dataset.originalSrc,delete a.dataset.originalSrc)},I=function(a){var d=m["default"].cardRoot.querySelectorAll("[data-text-color]"),
b=m["default"].cardRoot.querySelectorAll(".bannerWrapper"),c=q["default"].cardRoot.querySelector("._haul-cx-hero-carousel_pills_nav__ykWcb");0<d.length&&0<b.length&&c&&(a.on("change:pageNumber",function(f){(f=q["default"].cardRoot.querySelector('.a-carousel-card[aria-posinset="'+f.newPageNumber+'"] .bannerWrapper'))&&c.style.setProperty("--haulCardHeroTextColor",f.dataset.textColor||"")}),(a=q["default"].cardRoot.querySelector('.a-carousel-card[aria-posinset="1"] .bannerWrapper[data-text-color]'))&&
c.style.setProperty("--haulCardHeroTextColor",a.dataset.textColor||""))},J=function(){var a=m["default"].cardRoot.querySelector("[data-text-color]"),d=q["default"].cardRoot.querySelector("._haul-cx-hero-carousel_pills_nav__ykWcb");a&&d&&d.style.setProperty("--haulCardHeroTextColor",a.dataset.textColor||"")};r._operationNames=[];r.card=function(){return t.__awaiter(void 0,void 0,void 0,function(){var a,d,b,c,f,h,k,l,n,p;return t.__generator(this,function(e){switch(e.label){case 0:a=m["default"].cardRoot.getElementsByClassName("_haul-cx-hero-carousel_style_carouselData__2rioM")[0];
if(!a)return[2];d=x(a);b=E();m["default"].cardRoot.querySelector("[data-pause-btn]")&&(c=f=H({startFrozen:null!==(n=null===b||void 0===b?void 0:b.matches)&&void 0!==n?n:!1,root:a}),null===b||void 0===b?void 0:b.addEventListener("change",function(g){g.matches&&f.freezeAll()}));if(!d.shouldEnableCarousel)return J(),[2];h=m["default"].cardRoot.getElementsByClassName("a-carousel-container")[0];if(!h)return[2];k=D["default"].getCarousel(h);return[4,k.initialized];case 1:return e.sent(),l=F(k,d.rotationTime,
5E3),(null===b||void 0===b?0:b.matches)||l.start(),null===b||void 0===b?void 0:b.addEventListener("change",function(g){g.matches&&l.stop()}),null===(p=h.addEventListener)||void 0===p?void 0:p.call(h,"focusin",function(){return l.stop()}),k.on("change:pageNumber",function(g){g=g.newPageNumber;l.isAutoUpdate()||l.stop();l.resetAutoFlag();null===c||void 0===c?void 0:c.onSlideChange(g)}),I(k),[2]}})})};r.parseCarouselConfig=x});
