'use strict';mix_d("AmazonHaulInfiniteScrollWidgetsCards__h-isw-spotlight:h-isw-spotlight__x8ExuQea",["exports","tslib","@c/dom","@c/metrics"],function(u,v,q,r){function w(b,c,f,k){function g(l){m&&(m=!1,a.releasePointerCapture(l.pointerId),.5<Math.max(h/n,Math.max(0,Math.min(l.clientX-p,n))/n)?(a.style.transition="left 0.2s ease-out, opacity 0.3s",a.style.left=n+3+"px",k()):(r.count("card:h-isw-spotlight:dailydrop:swipe-abandon",1),a.classList.remove(t.dragging),a.style.transition="left 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)",
a.style.left="3px",d&&(d.style.opacity="1")),h=0)}var a=c.querySelector("[data-daily-drop-thumb]"),e=c.querySelector("[data-daily-drop-track]"),d=c.querySelector("[data-daily-drop-slider-text]");if(a&&e){var m=!1,p=0,h=0,n=0;a.addEventListener("pointerdown",function(l){m=!0;p=l.clientX;n=e.offsetWidth-a.offsetWidth-6;a.style.transition="none";a.classList.add(t.dragging);a.setPointerCapture(l.pointerId)});a.addEventListener("pointermove",function(l){m&&(l.preventDefault(),h=Math.max(0,Math.min(l.clientX-
p,n)),a.style.left=3+h+"px",l=h/n,d&&(d.style.opacity=String(1-l)))});a.addEventListener("pointerup",g);a.addEventListener("pointercancel",g);a.style.touchAction="none"}}function y(b,c,f){function k(){d||(d=setInterval(function(){m+=5;e.style.background="conic-gradient(var(--dropSliderColor, #6700CE) "+m+"%, transparent "+m+"%)";100<=m&&(d&&(clearInterval(d),d=null),f())},100))}function g(){d&&(clearInterval(d),d=null);100>m&&(r.count("card:h-isw-spotlight:dailydrop:hold-abandon",1),m=0,e.style.background=
"conic-gradient(var(--dropSliderColor, #6700CE) 0%, transparent 0%)")}var a=c.querySelector("[data-daily-drop-hold]"),e=c.querySelector("[data-daily-drop-hold-fill]");if(a&&e){var d=null,m=0;a.addEventListener("touchstart",k,{passive:!0});a.addEventListener("mousedown",k);b.addEventListener("touchend",g);b.addEventListener("mouseup",g)}}function z(b,c,f){(b.querySelector("flip"===c?"[data-daily-drop-flip]":"[data-daily-drop-tap]")||b).addEventListener("click",function(){return f()})}function A(b,
c){function f(h){if(d&&e){"touches"in h&&h.preventDefault();var n=a.getBoundingClientRect(),l="touches"in h?h.touches[0].clientX:h.clientX;h="touches"in h?h.touches[0].clientY:h.clientY;e.globalCompositeOperation="destination-out";e.beginPath();e.arc(l-n.left,h-n.top,16,0,2*Math.PI);e.fill();p++;if(0===p%5&&e){n=e.getImageData(0,0,a.width,a.height).data;l=0;for(h=3;h<n.length;h+=16)0===n[h]&&l++;.45<l/(m/4)&&(d=!1,c())}}}function k(){d&&(d=!1,r.count("card:h-isw-spotlight:dailydrop:scratch-abandon",
1))}var g=b.querySelector("[data-daily-drop-scratch-zone]"),a=b.querySelector("[data-daily-drop-scratch-canvas]");if(g&&a){var e=null,d=!1,m=0,p=0;setTimeout(function(){a.width=g.offsetWidth;a.height=g.offsetHeight;if(e=a.getContext("2d"))e.fillStyle="#c0c0c0",e.fillRect(0,0,a.width,a.height),e.font="bold 12px sans-serif",e.fillStyle="#8a8a8a",e.textAlign="center",e.fillText("SCRATCH HERE",a.width/2,a.height/2+4),m=a.width*a.height},100);a.addEventListener("touchstart",function(){d=!0},{passive:!0});
a.addEventListener("mousedown",function(){d=!0});a.addEventListener("touchend",k);a.addEventListener("mouseup",k);a.addEventListener("touchmove",f,{passive:!1});a.addEventListener("mousemove",f)}}function B(b){var c=b.ownerDocument.createElement("div");c.style.cssText="position:absolute;inset:0;z-index:20;pointer-events:none;overflow:hidden;";b.appendChild(c);var f=b.ownerDocument.createElement("div");f.style.cssText="position:absolute;inset:0;background:rgba(255,255,255,0.6);z-index:19;pointer-events:none;animation:confettiFlash 0.3s forwards;";
b.appendChild(f);setTimeout(function(){return f.remove()},300);for(var k=0;40>k;k++){var g=b.ownerDocument.createElement("span"),a=5+7*Math.random(),e=.5<Math.random();g.style.cssText="\n            position:absolute;\n            left:"+100*Math.random()+"%;\n            top:"+50*Math.random()+"%;\n            width:"+(e?.4*a:a)+"px;\n            height:"+a+"px;\n            background:"+x[Math.floor(Math.random()*x.length)]+";\n            border-radius:"+(e?"1px":"50%")+";\n            opacity:0;\n            animation:confettiBurst 1.2s forwards;\n            animation-delay:"+
.1*Math.random()+"s;\n        ";c.appendChild(g)}setTimeout(function(){return c.remove()},1400)}var C=q&&"object"===typeof q&&"default"in q?q:{"default":q},D=function(b){if(void 0!==b.dataset.isw){var c=b.dataset.iswPosition,f=b.dataset.iswSize||"S";void 0!==P&&void 0!==c&&P.when("h-isw-register").execute("h-isw-widget-registration",function(k){k.addWidget({getWidget:function(){var g;return null!==(g=b.parentElement)&&void 0!==g?g:b},getPosition:function(){return Number(c)},getSize:function(){return"S"==
f||"M"==f||"L"==f?f:"S"},show:function(){b.dataset.active="true"}})})}return!1},t={link:"_h-isw-spotlight_style_link__2zPSV",spotlight:"_h-isw-spotlight_style_spotlight__2JFkK",spotlightContent:"_h-isw-spotlight_style_spotlightContent__tlmRw",valueProp:"_h-isw-spotlight_style_valueProp__3X_rv",badgeText:"_h-isw-spotlight_style_badgeText__3P187",badgeSub:"_h-isw-spotlight_style_badgeSub__2RS4v",productCard:"_h-isw-spotlight_style_productCard__3Y97L",dailyDropMode:"_h-isw-spotlight_style_dailyDropMode__3B4-T",
unlocked:"_h-isw-spotlight_style_unlocked__3ltAB",dailyDropImageBadge:"_h-isw-spotlight_style_dailyDropImageBadge__TFtv7",dailyDropOverlay:"_h-isw-spotlight_style_dailyDropOverlay__3uvQA",sliderTrack:"_h-isw-spotlight_style_sliderTrack__1Ozr7",arrowsDrift:"_h-isw-spotlight_style_arrowsDrift__1pZ91",sliderText:"_h-isw-spotlight_style_sliderText__1gQAI",sliderThumb:"_h-isw-spotlight_style_sliderThumb__F_m9z",thumbPulse:"_h-isw-spotlight_style_thumbPulse__2q5iv",thumbNudge:"_h-isw-spotlight_style_thumbNudge__2jKPw",
dragging:"_h-isw-spotlight_style_dragging__AHlGI",gripDot:"_h-isw-spotlight_style_gripDot__2PzYO",dropInfo:"_h-isw-spotlight_style_dropInfo__1XEU1",dropTitleGroup:"_h-isw-spotlight_style_dropTitleGroup__AUkMo",dropTitle:"_h-isw-spotlight_style_dropTitle__3W8k-",dropHeadline:"_h-isw-spotlight_style_dropHeadline__1SY_w",dropSubtitle:"_h-isw-spotlight_style_dropSubtitle__3WzHV",scratchLabel:"_h-isw-spotlight_style_scratchLabel__2wE6P",mysteryIcon:"_h-isw-spotlight_style_mysteryIcon__38Z33",thumbIcon:"_h-isw-spotlight_style_thumbIcon__1q_i8",
holdCircle:"_h-isw-spotlight_style_holdCircle__3cUPd",holdFill:"_h-isw-spotlight_style_holdFill__AzK-_",holdIcon:"_h-isw-spotlight_style_holdIcon__3OH76",tapZone:"_h-isw-spotlight_style_tapZone__afm0a",tapIcon:"_h-isw-spotlight_style_tapIcon__2OmSW",tapWiggle:"_h-isw-spotlight_style_tapWiggle__OZmqj",scratchZone:"_h-isw-spotlight_style_scratchZone__1-vYl",scratchCanvas:"_h-isw-spotlight_style_scratchCanvas__2cJ1d",flipFront:"_h-isw-spotlight_style_flipFront__1bJsz",flipIcon:"_h-isw-spotlight_style_flipIcon__1lpEP",
flipHint:"_h-isw-spotlight_style_flipHint__1oTey",mysteryPulse:"_h-isw-spotlight_style_mysteryPulse__1E50R"},x=["#6700CE","#EF94FF","#FFE13E","#80DE9A","#84C9FF"];u._operationNames=[];u.card=function(){return v.__awaiter(void 0,void 0,void 0,function(){var b,c,f,k,g,a,e,d;return v.__generator(this,function(m){b=C["default"].cardRoot;if(!b||void 0===b.dataset.isw)return[2];D(b);c=b.querySelector("[data-daily-drop-overlay]");if(!c)return[2];f=b.querySelector("."+t.spotlight);if(!f)return[2];k="slide unblur flip hold tap scratch".split(" ");
g=f.dataset.dailyDropStyle||"slide";a=0<=k.indexOf(g)?g:"slide";r.count("card:h-isw-spotlight:dailydrop:impression:"+a,1);e=!1;d=function(){e||(e=!0,r.count("card:h-isw-spotlight:dailydrop:unlock:"+a,1),setTimeout(function(){return f.classList.add(t.unlocked)},200),setTimeout(function(){c.style.pointerEvents="none"},500),setTimeout(function(){var p=f.querySelector("[data-daily-drop-content]")||f;B(p)},600))};c.addEventListener("keydown",function(p){if("Enter"===p.key||" "===p.key)p.preventDefault(),
d()});switch(a){case "unblur":w(b,c,f,d);break;case "hold":y(b,c,d);break;case "tap":case "flip":z(c,a,d);break;case "scratch":A(c,d);break;default:w(b,c,f,d)}return[2]})})}});
