(function(d){var e=window.AmazonUIPageJS||window.P,k=e._namespace||e.attributeErrors,f=k?k("GeexCartProgressIndicatorAssets@FloatingBottomWidget","GeexCartProgressIndicatorAssets"):e;f.guardFatal?f.guardFatal(d)(f,window):f.execute(function(){d(f,window)})})(function(d,e,k){function f(a,b){try{d.register(a,b)}catch(g){g.message.indexOf("reregistered by GeexCartProgressIndicatorAssets")}}f("GeexCartProgressIndicatorFwAssetDuplicationGuard",function(){return{register:f,when:function(){var a=arguments;
return{register:function(b,g){try{d.when.apply(d,a).register(b,g)}catch(t){t.message.indexOf("reregistered by GeexCartProgressIndicatorAssets")}}}}}});"use strict";d.when("GeexCartProgressIndicatorFwAssetDuplicationGuard").execute(function(a){a.register("geex-FloatingBottomWidget-util-glow-ufg-config-storefront",function(){return[]})});"use strict";d.when("GeexCartProgressIndicatorFwAssetDuplicationGuard").execute(function(a){a.register("geex-FloatingBottomWidget-util-glow-ufg-config-category",function(){return[]})});
"use strict";d.when("GeexCartProgressIndicatorFwAssetDuplicationGuard").execute(function(a){a.when("geex-FloatingBottomWidget-util-glow-ufg-config-storefront","geex-FloatingBottomWidget-util-glow-ufg-config-category").register("geex-FloatingBottomWidget-util-glow-ufg-config",function(b,a){return{GLOW_SUPPRESSED_URL:[].concat(b).concat(a)}})});"use strict";d.when("GeexCartProgressIndicatorFwAssetDuplicationGuard").execute(function(a){a.when("geex-FloatingBottomWidget-util-glow-ufg-config").register("geex-FloatingBottomWidget-util-glow-ufg",
function(b){return{isGlowSuppressed:function(){var a=e.location.href,d=!0,l=!1,f=k;try{for(var m=b.GLOW_SUPPRESSED_URL[Symbol.iterator](),n;!(d=(n=m.next()).done);d=!0)if(a.includes(n.value))return!0}catch(h){l=!0,f=h}finally{try{!d&&m.return&&m.return()}finally{if(l)throw f;}}return!1}}})});"use strict";d.when("GeexCartProgressIndicatorFwAssetDuplicationGuard").execute(function(a){a.register("geex-FloatingBottomWidget-util-glow-pharmacy",function(){return{isGlowSuppressed:function(){return!1}}})});
"use strict";d.when("GeexCartProgressIndicatorFwAssetDuplicationGuard").execute(function(a){a.register("geex-FloatingBottomWidget-util-glow-retail",function(){var b=/^\/(?:[^/]+\/)?(?:s|gp\/search)(?:\.html)?(?:\/|$)/;return{isGlowSuppressed:function(){return!b.test(e.location.pathname)}}})});"use strict";d.when("GeexCartProgressIndicatorFwAssetDuplicationGuard").execute(function(a){a.when("A","geex-core-storage-context-program","geex-FloatingBottomWidget-util-glow-pharmacy","geex-FloatingBottomWidget-util-glow-retail",
"geex-FloatingBottomWidget-util-glow-ufg").register("geex-FloatingBottomWidget-util-glow",function(b,a,d,e,f){return{isGlowSuppressed:function(){if(!b.capabilities.isAmazonApp)return!1;var g=a.get("instance");if(b.objectIsEmpty(g))return!1;switch(g.getProgramType()){case "IN_PHARMACY":return d.isGlowSuppressed();case "HAUL":case "BAZAAR":return!0;case "RETAIL":return e.isGlowSuppressed();case "EverydayEssentials":return!0;case "UFG":return f.isGlowSuppressed();default:return!1}}}})});"use strict";
"use strict";d.when("GeexCartProgressIndicatorFwAssetDuplicationGuard").execute(function(a){a.when("A","3p-promise","geex-FloatingBottomWidget-util-glow","geex-core-storage-context-program").register("geex-core-helper-positionhelper",function(b,a,f,l){var g=["a:sheet:beforeHide","a:popover:beforeSlideOut"],m=["a:sheet:afterShow","a:popover:afterSlide"],n=["AlmBeforeYouGoWebview","AlmBeforeYouGoAW","Upsell"],h={},u=new URLSearchParams(e.location.search),t="BAZAAR"===l.get("instance").getProgramType()&&
("bazaar"===u.get("s")||"specialOffer"===u.get("merchPageId")||"byg"===u.get("merchPageId")),p="HAUL"===l.get("instance").getProgramType()||"BAZAAR"===l.get("instance").getProgramType(),y="RETAIL"===l.get("instance").getProgramType();p&&requestAnimationFrame(function(){return b.$("body").css("min-height","100vh")});var v=void 0,A=function(){return new a(function(a,z){d.when("MShopChrome").execute(function(c){b.objectIsEmpty(c)||"function"!==typeof c.getBottomBarsHeight||c.getBottomBarsHeight({successCallback:function(b){a(b)},
failCallback:function(){z()}})})})},B=function(a){var q=1<arguments.length&&arguments[1]!==k?arguments[1]:!1;r()||(b.on(b.constants.BROWSER_EVENTS.SCROLL,function(){return a()}),q&&(m.forEach(function(c){return b.on(c,function(){return a(!0)})}),g.forEach(function(c){return b.on(c,function(){return a()})})),d.when("mash").execute(function(a){a&&a.addEventListener("bottomBarsUpdate",function(a){if(a&&a.detail){var c=a.detail.visibleHeight||0;b.capabilities.ios&&48===a.detail.tabBarHeight&&(c+=8);h.bottomChromeHeight=
c}})}))},w=function(a,b,c){requestAnimationFrame(function(){return b(a)});B(function(c){return requestAnimationFrame(function(){return b(a,c)})},c)},C=function(a){if(1<arguments.length&&arguments[1]!==k&&arguments[1]||r()||0===h.bottomChromeHeight)a.css("margin-bottom",0);else{var b=e.document.documentElement.scrollTop,c=f.isGlowSuppressed()?0:.75*h.bottomChromeHeight;a.css("margin-bottom",Math.max(c-b,0))}},D=function(a){if(1<arguments.length&&arguments[1]!==k&&arguments[1]||r()||0===h.bottomChromeHeight)a.css("margin-bottom",
0);else{var b=e.document.documentElement,c=b.clientHeight,d=b.scrollTop;b=b.scrollHeight-(d+c);var g=h.bottomChromeHeight;c=y?Math.max(c-e.innerHeight,0):10;c=f.isGlowSuppressed()?0:c;var q=h.bottomChromePadding||0,l=b-q;0>=d?(p&&e.clearTimeout(v),a.css("margin-bottom",g+c)):p&&500>l?(d=a.outerHeight(),b=parseInt(a.css("bottom"),10),a.css("margin-bottom",-(d+b)),e.clearTimeout(v),v=e.setTimeout(function(){a.css("margin-bottom",Math.min(g,Math.max(g+(document.documentElement.scrollHeight-(document.documentElement.scrollTop+
document.documentElement.clientHeight+q)),0)))},1E3)):0>=b?a.css("margin-bottom",0):a.css("margin-bottom",g)}},r=function(){return-1<b.indexOfArray(n,e.ue_spty)||t},x=function(a,d){var c=b.reduce([".byg-mobile-floating-box",".byg-mobile-continue-button",'.floating-box:has(span[id\x3d"subsContinueButton"])'],function(a,c){return a+b.$(c).height()},0);c+=b.reduce(["#haul-buybox-wrapper","#bazaar_buybox_mobile #wrapper","#bazaar_buybox_mobileApp #wrapper","#bz-gtb-container","#bz-byg-container"],function(a,
c){return a+b.$(c).outerHeight()},0);a.css("bottom",c);d.css("margin-bottom",c)};return{registerBottomMarginHandlers:function(){var a=0<arguments.length&&arguments[0]!==k?arguments[0]:b.$("#geex-floatingBottomWidget"),g=1<arguments.length&&arguments[1]!==k?arguments[1]:b.$("#geex-floatingBottomWidget-offset");x(a,g);d.when("ready").execute(function(){return x(a,g)});0!==b.$(a).length&&b.capabilities.isAmazonApp&&!r()&&A().then(function(c){var d=c.visibleHeight;b.capabilities.ios&&48===c.tabBarHeight&&
(d+=8);h.bottomChromeHeight=d;p&&b.capabilities.ios&&c.visibleHeight&&c.tabBarHeight&&(h.bottomChromePadding=Math.max(c.visibleHeight-c.tabBarHeight,0));b.capabilities.android?w(a,C):b.capabilities.ios&&w(a,D,!0)}).catch(function(){})}}})});"use strict";d.when("GeexCartProgressIndicatorFwAssetDuplicationGuard").execute(function(a){a.when("A").register("geex-core-registry-declarative",function(a){a.declarative("geex-link-redirection","click",function(b){a.objectIsEmpty(b)||a.objectIsEmpty(b.data)||
!(b=b.data.redirectUrl)||(e.location.href=b)})})})});