'use strict';(function(d){var b=window.AmazonUIPageJS||window.P,k=b._namespace||b.attributeErrors,a=k?k("PromotionsCartAssets",""):b;a.guardFatal?a.guardFatal(d)(a,window):a.execute(function(){d(a,window)})})(function(d,b,k){d.when("A","PromotionsActionHandlerFactory","PromotionsCSMUtil").execute(function(a,e,g){a.declarative("promotion-cta-link","click",function(c){g.logUECounter("PromotionCtaLink",1);var a=c.data;c=c.$target;e.get(a).execute(a,c)})});"use strict";d.when("A","PromoRedirectActionHandler",
"PromoModalActionHandler","PromoRedeemActionHandler","PromoMiniPspRedirectActionHandler").register("PromotionsActionHandlerFactory",function(a,e,g,c,b){return{get:function(a){a=a.linkUrl;return a.includes("redeem")?c:a.includes("minipsp")?b:a.includes("popup")?g:e}}});"use strict";d.when("A","PromotionsCSMUtil").register("PromoRedirectActionHandler",function(a,e){return{execute:function(a,c){e.logUECounter("PromotionRedirectAction",1);b.location.href=a.linkUrl}}});"use strict";d.when("A","a-modal",
"PromoRedirectActionHandler","PromotionsCSMUtil").register("PromoModalActionHandler",function(a,e,g,c){return{execute:function(d,m){c.logUECounter("PromotionModalAction",1);a.ajax(d.linkUrl,{method:"get",success:function(a){c.logUECounter("PromotionModalAction:Success",1);e.create(m,{name:"UnifiedPromotionModal",inlineContent:a,dataStrategy:"inline"}).show()},error:function(){c.logUECounter("PromotionModalAction:Failure",1);var a=new URL(d.linkUrl,b.location.origin);if(a=(new URLSearchParams(a.search)).get("redirectLandingPageUrl"))c.logUECounter("PromotionModalAction:Failure:Fallback",
1),g.execute({linkUrl:a})}})}}});"use strict";d.when("A","a-sheet","PromoRedirectActionHandler","PromotionsCSMUtil").register("PromoBottomSheetActionHandler",function(a,e,g,c){return{execute:function(d,m){c.logUECounter("PromotionBottomSheetAction",1);a.ajax(d.linkUrl,{method:"get",success:function(b){c.logUECounter("PromotionBottomSheetAction:Success",1);e.create({name:"UnifiedPromotionBottomSheet",inlineContent:b,closeType:"icon",height:600}).show();a.trigger("UnifiedPromotionBottomSheet:Show",
d)},error:function(){c.logUECounter("PromotionBottomSheetAction:Failure",1);var a=new URL(d.linkUrl,b.location.origin);if(a=(new URLSearchParams(a.search)).get("redirectLandingPageUrl"))c.logUECounter("PromotionBottomSheetAction:Failure:Fallback",1),g.execute({linkUrl:a})}})}}});"use strict";d.when("A","PromotionsCSMUtil").register("PromoRedeemActionHandler",function(a,e){function b(a){e.logUECounter("PromotionRedeemAction:Failure",1);a.ajaxFailMessage&&alert(a.ajaxFailMessage)}return{execute:function(c,
d){e.logUECounter("PromotionRedeemAction",1);a.ajax(c.linkUrl,{method:"get",success:function(c){if(c.includes&&(c.includes("FAILURE")||c.includes("EXCEEDED"))||0==c.status)b();else{e.logUECounter("PromotionRedeemAction:Success",1);c=a.$(d).closest(".sc-unified-promotion-widget");var g=c.find(".sc-unified-promotion-message-wrapper");a.hide(g);c=c.find(".sc-unified-promotion-success-message-wrapper");a.show(c)}},error:function(){b(c)}})}}});"use strict";d.when("A","PromoRedirectActionHandler","PromotionsCSMUtil").register("PromoMiniPspRedirectActionHandler",
function(a,e,d){return{execute:function(a,g){d.logUECounter("PromoMiniPspRedirectAction",1);a=new URL(a.linkUrl,b.location.origin);(a=(new URLSearchParams(a.search)).get("redirectLandingPageUrl"))&&e.execute({linkUrl:a})}}});"use strict";d.when("A","PromotionsCSMUtil").execute(function(a,d){function e(){d.logUECounter("PromoMiniPspCloseAction",1);b&&b.location&&b.location.reload()}a.on("UnifiedPromotionBottomSheet:Show",function(c){if(c.linkUrl.includes("minipsp"))a.on("a:sheet:beforeHide:UnifiedPromotionBottomSheet",
e)})});"use strict";d.when("A").execute(function(a){function d(a,h){"undefined"!==typeof ue&&ue.count&&ue.count(a,h)}function g(a,h){if(a)try{var c=a.querySelector(f.SELECTORS.COUPON_CHECKBOX);if(c){var d;if(d=c.tagName&&"input"===c.tagName.toLowerCase()?c:c.querySelector(f.SELECTORS.CHECKBOX_INPUT))d.checked=h}}catch(r){}}function c(a,c){a:if(c){try{var h=c.querySelector(f.SELECTORS.FAILURE_TEXT+a);if(h){var b=h.getAttribute(f.SELECTORS.DATA_FAILURE_TEXT_ATTRIBUTE);break a}}catch(r){}b=void 0}else b=
"Unknown error occurred.";alert(b);d(f.ANALYTICS_EVENTS.POSTCLAIM_FAILURE,1);c&&g(c,!1);a&&delete n[a]}function k(b,h,e){b?a.ajax(b,{method:f.REQUEST.METHOD,params:m(h),paramsFormat:f.REQUEST.PARAMS_FORMAT,success:function(b){delete n[e.promotionId];if(!b||-1===b.indexOf(f.RESPONSE.FAILURE_INDICATORS[0])&&-1===b.indexOf(f.RESPONSE.FAILURE_INDICATORS[1])){a.trigger("affordability:clipCoupon:success");if((b=e.promotionId)&&h)try{var l=h.closest(f.SELECTORS.COUPON_COMPONENT);if(l){var g=l.querySelector(f.SELECTORS.COUPON_TILE_PREFIX+
b);if(g)g.classList.add(f.CSS_CLASSES.HIDDEN);else{var q=l.querySelector(f.SELECTORS.UNCLAIMED_TILE);q&&q.classList.add(f.CSS_CLASSES.HIDDEN)}var k=l.querySelector(f.SELECTORS.DONE_TILE_PREFIX+b);if(k)k.classList.remove(f.CSS_CLASSES.HIDDEN),(0<=k.tabIndex||k.getAttribute("role"))&&k.focus();else{var m=l.querySelector(f.SELECTORS.CLAIMED_WRAPPER);m&&m.classList.remove(f.CSS_CLASSES.HIDDEN)}}}catch(u){}d(f.ANALYTICS_EVENTS.POSTCLAIM_SUCCESS,1)}else c(e.promotionId,h)},error:function(){c(e.promotionId,
h)}}):c(e.promotionId,h)}function m(a){a=JSON.parse(a.getAttribute(f.SELECTORS.COUPON_CLAIM_PARAMS));var c=[],b;for(b in a)c.push(b+"\x3d"+a[b]);return c.join("\x26")}function p(a){var b=a.$event;b&&(b.preventDefault&&b.preventDefault(),b.stopPropagation&&b.stopPropagation(),b.stopImmediatePropagation&&b.stopImmediatePropagation());b=a.$target;var d=null;a.$declarativeParent&&0<a.$declarativeParent.length?d=a.$declarativeParent[0]:b&&0<b.length&&(d=b[0].closest(f.SELECTORS.COUPON_CLAIM_ACTION));if(b=
d){g(b,!0);a:{if(b)try{var e=b.querySelector(f.SELECTORS.CLAIM_URL+a.data.promotionId);if(e){var l=e.getAttribute(f.SELECTORS.DATA_CLAIM_URL_ATTRIBUTE);break a}}catch(t){}l=void 0}a=a.data;n[a.promotionId]||(n[a.promotionId]=!0,l?k(l,b,a):c(a.promotionId,b))}}var n={},f={KEYCODES:{ENTER:13,SPACE:32},SELECTORS:{COUPON_COMPONENT:".apex-coupon-tile-container",COUPON_TILE_PREFIX:"#couponTile",DONE_TILE_PREFIX:"#doneTile",UNCLAIMED_TILE:".apex-coupon-tile.unclaimed",CLAIMED_WRAPPER:".apex-claimed-wrapper",
COUPON_CLAIM_ACTION:'[data-action\x3d"coupon-claim"]',COUPON_CLAIM_PARAMS:"data-coupon-claim",COUPON_CHECKBOX:".apex-coupon-checkbox",CHECKBOX_INPUT:"input",CLAIM_URL:"#claimUrl",DATA_CLAIM_URL_ATTRIBUTE:"data-claim-url",FAILURE_TEXT:"#failureText",DATA_FAILURE_TEXT_ATTRIBUTE:"data-failure-text"},ANALYTICS_EVENTS:{POSTCLAIM_SUCCESS:"promoPostclaimSuccess",POSTCLAIM_FAILURE:"promoPostclaimFailure"},REQUEST:{METHOD:"post",PARAMS_FORMAT:"string"},RESPONSE:{FAILURE_INDICATORS:["FAILURE","EXCEEDED"]},
CSS_CLASSES:{HIDDEN:"aok-hidden"}};b.couponHandlersInitialized||(function(){a.declarative("coupon-claim","click",function(a){p(a)});a.declarative("coupon-claim","keydown",function(a){var b=(b=a.$event)&&b.keyCode?b.keyCode===f.KEYCODES.ENTER||b.keyCode===f.KEYCODES.SPACE:!1;b&&p(a)})}(),b.couponHandlersInitialized=!0)});"use strict";"use strict";d.when("A").register("PromotionsCSMUtil",function(a){return{logUECounter:function(a,d){"undefined"!==typeof b.ue&&"undefined"!==typeof b.ue.count&&b.ue.count("PromotionsCartAssets:"+
a,d||1)}}});"use strict";d.when("A").register("WeblabUtil",function(a){return{trigger:function(a,d){"undefined"!==typeof b.ue&&"function"===typeof b.ue.trigger&&b.ue.trigger(a,d)}}})});