'use strict';mix_d("AmazonLuxuryWidgetCards__lux-splash-screen:lux-splash-screen__M7DKFkDG","require exports tslib @c/scoped-dom @c/dom @c/aui-feature-detect @p/A".split(" "),function(z,u,g,I,A,J,K){function v(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function B(a){if(a&&a.__esModule)return a;var b=Object.create(null);a&&Object.keys(a).forEach(function(c){if("default"!==c){var d=Object.getOwnPropertyDescriptor(a,c);Object.defineProperty(b,c,d.get?d:{enumerable:!0,get:function(){return a[c]}})}});
b["default"]=a;return b}var C=v(I),L=v(A),M=v(J),D=v(K),t=null,q=null,E=function(){try{return M["default"].isSupported("isAmazonApp")}catch(a){return!1}},N=function(){return g.__awaiter(void 0,void 0,void 0,function(){var a,b;return g.__generator(this,function(c){switch(c.label){case 0:if(!E())return[2];c.label=1;case 1:return c.trys.push([1,3,,4]),[4,new Promise(function(d,e){z(["@m/mash"],function(f){d(B(f))},e)})];case 2:return a=c.sent().requestFullscreen,D["default"].capabilities.ios&&(t=A.cardRoot().ownerDocument.head.querySelector("meta[name='viewport']"))&&
(q=t.getAttribute("content"),t.setAttribute("content",(null!==q&&void 0!==q?q:"")+", viewport-fit=cover")),b={hideSystemBars:!0},a(b),[3,4];case 3:return c.sent(),[3,4];case 4:return[2]}})})},O=function(){return g.__awaiter(void 0,void 0,void 0,function(){var a;return g.__generator(this,function(b){switch(b.label){case 0:if(!E())return[2];b.label=1;case 1:return b.trys.push([1,3,,4]),[4,new Promise(function(c,d){z(["@m/mash"],function(e){c(B(e))},d)})];case 2:return a=b.sent().cancelFullscreen,D["default"].capabilities.ios&&
t&&null!==q&&t.setAttribute("content",q),a({}),[3,4];case 3:return b.sent(),[3,4];case 4:return[2]}})})},P=function(){for(var a,b,c,d,e=[],f=0;f<arguments.length;f++)e[f]=arguments[f];try{for(var m=g.__values(e),l=m.next();!l.done;l=m.next()){var k=l.value;if(k&&k.isConnected)return k}}catch(n){a={error:n}}finally{try{l&&!l.done&&(b=m.return)&&b.call(m)}finally{if(a)throw a.error;}}try{for(var p=g.__values(e),h=p.next();!h.done;h=p.next())if(k=h.value)return k}catch(n){c={error:n}}finally{try{h&&
!h.done&&(d=p.return)&&d.call(p)}finally{if(c)throw c.error;}}return null},Q=function(a,b){void 0===b&&(b={});var c=b.requireRenovation;b=b.slotFilter;if(!a)return null;try{if((void 0===c||c)&&"true"!==a.getAttribute("data-fall-renovation"))return null;var d=a.closest(".apb-default-slot");if(!d||b&&!b(d))return null;d.style.marginTop="0";d.style.marginBottom="0";return d}catch(e){return null}},R={requireRenovation:!1,slotFilter:function(a){return a.matches('[class*="apb-default-mobile-"]')}},S=function(a,
b){return new Promise(function(c){var d=a.ownerDocument?a.ownerDocument.defaultView:null;if(d&&d.matchMedia&&d.matchMedia("(prefers-reduced-motion: reduce)").matches)c();else{var e=!1,f=function(){e||(e=!0,a.removeEventListener("transitionend",f),c())};a.addEventListener("transitionend",f,{once:!0});setTimeout(f,b)}})},F=function(a,b){b="lux-splash-shown:"+b;try{if("session"===a)return"1"===sessionStorage.getItem(b);if("daily"===a)return localStorage.getItem(b)===(new Date).toISOString().slice(0,
10)}catch(c){}return!1},G=function(a,b){b="lux-splash-shown:"+b;try{"session"===a?sessionStorage.setItem(b,"1"):"daily"===a&&localStorage.setItem(b,(new Date).toISOString().slice(0,10))}catch(c){}};u._operationNames=[];u.card=function(){return g.__awaiter(void 0,void 0,void 0,function(){var a,b,c,d,e,f,m,l,k,p,h,n,w,x,y;return g.__generator(this,function(H){switch(H.label){case 0:Q(P(L["default"].cardRoot,C["default"].cardRoot),R);a=C["default"].cardRoot.querySelector("._lux-splash-screen_style_overlay__1_uyL");
if(!a)return[2];b=a.getAttribute("data-splash-frequency")||"always";c=a.getAttribute("data-splash-content-id")||"lux-splash-screen";d=parseInt(a.getAttribute("data-splash-duration")||"",10)||5E3;e=parseInt(a.getAttribute("data-splash-fade-out")||"",10);f=isNaN(e)?300:e;isNaN(e)||a.style.setProperty("--splash-fade-out-ms",f+"ms");m=f+200;if(F(b,c))return a.remove(),[2];G(b,c);if(l=a.getAttribute("data-splash-bg"))a.style.backgroundColor=l;a.classList.remove("_lux-splash-screen_style_hidden__2dTkA");
return[4,N()];case 1:H.sent();if(k=a.querySelector("video"))k.muted=!0,k.play().catch(function(){});h=(p=a.ownerDocument)?p.activeElement:null;n=!1;w=function(){return g.__awaiter(void 0,void 0,void 0,function(){return g.__generator(this,function(r){switch(r.label){case 0:if(n)return[2];n=!0;a.removeEventListener("click",x);a.removeEventListener("keydown",y);a.classList.add("_lux-splash-screen_style_fadeOut__1rOmB");return[4,S(a,m)];case 1:return r.sent(),[4,O()];case 2:return r.sent(),h&&"function"===
typeof h.focus&&h.focus(),a.remove(),[2]}})})};x=function(){void w()};y=function(r){"Escape"!==r.key&&"Esc"!==r.key||void w()};a.addEventListener("click",x);a.addEventListener("keydown",y);"function"===typeof a.focus&&a.focus();setTimeout(function(){void w()},d);return[2]}})})};u.isCapped=F;u.markShown=G});
