'use strict';mix_d("PrimeAcquisitionCXCards__slash-prime-hero-widget-desktop-card:slash-prime-hero-widget-desktop-card__-O7TBjI6","exports tslib @c/scoped-dom @c/logger @c/aui-untrusted-ajax @c/aui-modal @c/browser-operations".split(" "),function(B,k,D,E,F,G,H){function w(d){return d&&"object"===typeof d&&"default"in d?d:{"default":d}}function C(d,b){return k.__awaiter(this,void 0,void 0,function(){var c;return k.__generator(this,function(e){try{return c={accepts:"application/json",contentType:"application/json;charset=UTF-8",
additionalHeaders:I({})},[2,J["default"].post(b,c,d).then(function(a){(a=a.responseBody.payload.requestSuccess)||p["default"].log("Request the customer name ajax failed","ERROR");return a}).catch(function(a){p["default"].log("An error occurred while publishing metrics",a);return!1})]}catch(a){p["default"].log("Request the customer name ajax failed with the error:"+a,"ERROR")}return[2,!1]})})}function I(d){var b=(b=x["default"].cardRoot.querySelector("meta[name='anti-csrftoken-a2z']"))?b.getAttribute("content"):
"";d["anti-csrftoken-a2z"]=b;return d}function K(d){var b;return k.__awaiter(this,void 0,void 0,function(){var c,e,a,f,g,m,h,l,n,u;return k.__generator(this,function(y){c=d.cardRoot;e=d.cardId;a=d.painterId;f=d.style;g=null!==(b=L(c))&&void 0!==b?b:"en_US";m=new Map([["heading","<span>"+(z[g]||z.en_US)+"</span>"]]);t.initialize("/prime-ajax/acquisition/metrics",e,c,a);t.publishImpression();t.publishMetricWithCoreDimensions("Impression");t.publishSpecificButtonClick("plp-hero-cta","signupMetric");
M(c,f.hidden,m);h=c.querySelector("#plp-hero-cta");l=c.querySelector("form");n=!1;u=function(r){if(n)return r.preventDefault(),!1;n=!0;h&&(h.classList.add("a-button-disabled"),h.disabled=!0);setTimeout(function(){n=!1;h&&(h.classList.remove("a-button-disabled"),h.disabled=!1)},3E3);return!0};l&&l.addEventListener("submit",u);h&&h.addEventListener("click",function(r){if(n)return r.preventDefault(),r.stopPropagation(),!1});return[2]})})}function N(d,b,c,e,a){var f=O["default"].create(d+"-modal","."+
d+"-modal-wrapper",{a11yOpenMessage:b,closeButton:c,width:e,height:a});d=H.setup();d.define("openModal",["click"],function(){f.show()});d.define("hideModal",["click"],function(){f.hide()});b=x["default"].cardRoot.getElementsByClassName("button-show")[0];d.attach("openModal",b);b=x["default"].cardRoot.getElementsByClassName("modal-close-button")[0];d.attach("hideModal",b)}var x=w(D),p=w(E),J=w(F),O=w(G),P={welcome:"_c2xhc_welcome_m-HZy",example:"_c2xhc_example_N6fPc",serverMsg:"_c2xhc_serverMsg_3Xh8N",
clientUpdate:"_c2xhc_clientUpdate_2uInn",focusVisible:"_c2xhc_focus-visible_1GD0A",hidden:"_c2xhc_hidden_wKXzm",activationError:"_c2xhc_activationError_3H7PL",slashPrimeHeroTncWrapper:"_c2xhc_slash-prime-hero-tnc-wrapper_2jamX",heroBadgeWrapper:"_c2xhc_hero-badge-wrapper_GPYUI"};({"prime-customer-name-field":""});var v;(v||(v={})).Count="Count";var Q=function(){function d(b){this.endpoint=b.endpoint}d.prototype.publishImpressionMetric=function(b,c,e){var a=v.Count;c=this.getStandardEventData(b,c,
e);null===c?p["default"].log("Event data is null and it indicates the DOM associated to the class isn't available","WARN"):this.publishMetric("Impression",1,a,c,b,this.endpoint)};d.prototype.publishButtonClickMetric=function(b,c){var e=this,a=v.Count,f=this.getStandardEventData(b,c);null===f?p["default"].log("Event data is null and it indicates the DOM associated to the class isn't available","WARN"):(c=document.querySelectorAll(".".concat(b," button")),0===c.length?p["default"].log("No buttons found for the given class",
"WARN"):c.forEach(function(g){g.addEventListener("click",function(){e.publishMetric("ButtonClick",1,a,f,b,e.endpoint)})}))};d.prototype.publishSpecificButtonClickMetric=function(b,c,e,a,f){var g=this,m=v.Count,h=this.getStandardEventData(b,a,f);null===h?p["default"].log("Event data is null and it indicates the DOM associated to the class isn't available","WARN"):(a=document.querySelector('[class*="'.concat(c,'"], [id*="').concat(c,'"]')))?a.addEventListener("click",function(){g.publishMetric(e,1,
m,h,b,g.endpoint)}):p["default"].log("Button with selector ".concat(c," not found"),"WARN")};d.prototype.publishCustomMetric=function(b,c,e,a){a=this.extractDimensionsForAdditionalEventData(a);a=Object.fromEntries(a);C({metricName:c,metricValue:e,metricUnit:v.Count,dimensions:a,location:b},this.endpoint)};d.prototype.publishMetric=function(b,c,e,a,f,g){a=this.extractDimensions(a);a=Object.fromEntries(a);C({metricName:b,metricValue:c,metricUnit:e,dimensions:a,location:f},g)};d.prototype.getStandardEventData=
function(b,c,e){return(e=document.querySelector('[class^="'.concat(b,'"], [id^="').concat(b,'"]'))||document.querySelector('div[data-csa-c-painter="'.concat(e,'"]')))?(b={cardName:e.getAttribute("data-csa-c-painter")||b,widgetId:e.getAttribute("data-csa-c-widget-id")||"",pageId:e.getAttribute("data-csa-c-page-id")||"",deviceType:e.getAttribute("data-csa-c-device-type")||""},k.__assign(k.__assign({},b),c)):null};d.prototype.extractDimensions=function(b){var c,e=new Map;try{for(var a=k.__values(Object.entries(b)),
f=a.next();!f.done;f=a.next()){var g=k.__read(f.value,2),m=g[0],h=g[1];"string"!==typeof h&&"number"!==typeof h||""===h.toString()||e.set(m,h.toString())}}catch(n){var l={error:n}}finally{try{f&&!f.done&&(c=a.return)&&c.call(a)}finally{if(l)throw l.error;}}return e};d.prototype.extractDimensionsForAdditionalEventData=function(b){var c,e=new Map;try{for(var a=k.__values(Object.entries(b)),f=a.next();!f.done;f=a.next()){var g=k.__read(f.value,2),m=g[0],h=g[1];"string"!==typeof h&&"number"!==typeof h||
""===h.toString()||e.set(m,h.toString())}}catch(n){var l={error:n}}finally{try{f&&!f.done&&(c=a.return)&&c.call(a)}finally{if(l)throw l.error;}}return e};return d}(),t=function(){function d(){this._state=null}d.getInstance=function(){d.instance||(d.instance=new d);return d.instance};d.prototype.extractMetadata=function(b){var c,e,a,f,g,m,h,l,n,u;b=(b.querySelector("[data-csa-c-metadata-map]")||b).getAttribute("data-csa-c-metadata-map");var y={};if(b)try{var r=JSON.parse(b),q=r.metadataMap?JSON.parse(r.metadataMap):
{},R=k.__assign({offerType:null!==(c=q.offerType)&&void 0!==c?c:"NONE",benefitRestrictionType:null!==(e=q.benefitRestrictionType)&&void 0!==e?e:"NONE",offerSegment:null!==(a=q.offerSegment)&&void 0!==a?a:"NONE",feeType:null!==(f=q.feeType)&&void 0!==f?f:"NONE",benefitTier:null!==(g=q.benefitTier)&&void 0!==g?g:"NONE",variantId:null!==(m=q.variantId)&&void 0!==m?m:"NONE",offerListingId:null!==(h=q.offerListingId)&&void 0!==h?h:"NONE",experimentTagMetadata:null!==(l=q.experimentTagMetadata)&&void 0!==
l?l:"NONE"},q.multiplan?{multiplan:q.multiplan}:{}),S={marketingContentCreativeId:null!==(n=r.marketingContentCreativeId)&&void 0!==n?n:"NONE",acquisitionDevice:null!==(u=r.acquisitionDevice)&&void 0!==u?u:"NONE"};y=k.__assign(k.__assign({},R),S)}catch(T){p["default"].log("Error parsing analyticalMetadataMap:"+T,"ERROR")}return y};d.prototype.initialize=function(b,c,e,a){var f=this.extractMetadata(e);e=e.querySelector("[data-csa-c-widget-id]")||e;var g=e.getAttribute("data-csa-c-widget-id")||"";this._state=
{publisher:new Q({endpoint:b}),cardName:c,csaAttributes:f,painterId:a,widgetId:g,pageId:e.getAttribute("data-csa-c-page-id")||"",deviceType:e.getAttribute("data-csa-c-device-type")||""}};d.prototype.publishImpression=function(b){var c=this.getState();c.publisher.publishImpressionMetric(c.cardName,k.__assign(k.__assign({},c.csaAttributes),b),c.painterId)};d.prototype.publishMetricWithCoreDimensions=function(b,c){void 0===c&&(c=1);var e=this.getState();e.publisher.publishCustomMetric(e.cardName,b,c,
{widgetId:e.widgetId,acquisitionDevice:e.csaAttributes.acquisitionDevice||""})};d.prototype.publishMetricWithVariantOnly=function(b,c){void 0===c&&(c=1);var e=this.getState();e.publisher.publishCustomMetric(e.cardName,b,c,{widgetId:e.widgetId,variantId:this.getVariantId()})};d.prototype.getVariantId=function(){return this.getState().csaAttributes.variantId||""};d.prototype.publishSpecificButtonClickWithMultiplan=function(b,c,e){var a=this.getState();a.csaAttributes.multiplan&&(b=e.querySelector("#"+
b))&&b.addEventListener("click",function(){a.publisher.publishCustomMetric(a.cardName,c,1,k.__assign({cardName:a.cardName,widgetId:a.widgetId,pageId:a.pageId,deviceType:a.deviceType},a.csaAttributes))})};d.prototype.publishButtonClick=function(b){var c=this.getState();c.publisher.publishButtonClickMetric(c.cardName,k.__assign(k.__assign({},c.csaAttributes),b))};d.prototype.publishSpecificButtonClick=function(b,c,e){var a=this.getState();a.publisher.publishSpecificButtonClickMetric(a.cardName,b,c,
k.__assign(k.__assign({},a.csaAttributes),e),a.painterId)};d.prototype.publishSpecificButtonClickWithVariantOnly=function(b,c,e){var a=this,f=this.getState();e.querySelectorAll("#"+b).forEach(function(g){g.addEventListener("click",function(){f.publisher.publishCustomMetric(f.cardName,c,1,{widgetId:f.widgetId,variantId:a.getVariantId()})})})};d.prototype.publishCustomMetric=function(b,c,e){var a=this.getState();a.publisher.publishCustomMetric(a.cardName,b,c,k.__assign(k.__assign({cardName:a.cardName},
a.csaAttributes),e))};d.prototype.getState=function(){if(!this._state)throw Error("MetricsService must be initialized before use");return this._state};return d}().getInstance(),U=/\s+/,V=/\$\$shorten-name\((.*?)\)\$\$/g,A=/\?SIEGE/g,W=function(d,b,c){if(!d)return!1;Array.from(d.getElementsByTagName("*")).filter(function(e){return!e.querySelector("*")&&(e.innerHTML.includes("$$shorten-name")||e.innerHTML.match(A))}).forEach(function(e){e.innerHTML=e.innerHTML.replace(V,function(a,f){a=f.split(U);return 2>
a.length?f:b.has(a[0].toUpperCase())||b.has(a[0].toUpperCase()+".")?a[1]:a[0]});e.innerHTML.match(A)&&(null!==c?(t.publishCustomMetric("siege.customer.name.decrypt.failure.fallback_used",1),t.publishMetricWithCoreDimensions("siege.customer.name.decrypt.failure.fallback_used"),d.innerHTML=c):(t.publishCustomMetric("siege.customer.name.decrypt.failure.no_fallback",1),t.publishMetricWithCoreDimensions("siege.customer.name.decrypt.failure.no_fallback")))});return null==d.innerHTML.match(A)},M=function(d,
b,c){var e=new Set;try{var a=d.querySelector("[data-prime-customer-name-titles]"),f=null===a||void 0===a?void 0:a.getAttribute("data-prime-customer-name-titles");e=new Set(JSON.parse(f))}catch(g){p["default"].log("Error getting title set data:"+g,"ERROR")}d.querySelectorAll("[data-prime-customer-name-field]").forEach(function(g){var m,h=!1;try{var l=g.getAttribute("data-prime-customer-name-fallback-key"),n=null!==(m=c.get(null!==l&&void 0!==l?l:""))&&void 0!==m?m:null;h=W(g,e,n)}finally{h&&(g.classList.remove(b),
g.removeAttribute("aria-hidden"))}})},z={en_US:"Join Prime today",es_US:"\u00danete a Prime hoy",ar_AE:"\u0627\u0634\u062a\u0631\u0643 \u0641\u064a \u0628\u0631\u0627\u064a\u0645 \u0627\u0644\u0622\u0646",en_AE:"Join Prime today",bn_IN:"\u0986\u099c\u0987 \u09aa\u09cd\u09b0\u09be\u0987\u09ae\u09c7 \u09af\u09cb\u0997 \u09a6\u09bf\u09a8",cs_CZ:"P\u0159ipojte se k Prime je\u0161t\u011b dnes",da_DK:"Bliv medlem af Prime i dag",de_DE:"Werde noch heute Prime-Mitglied",en_AU:"Join Prime today",en_CA:"Join Prime today",
en_GB:"Join Prime today",en_IE:"Join Prime today",en_IN:"Join Prime today",en_SG:"Join Amazon Prime today",en_ZA:"Join Amazon Prime today",es_ES:"\u00danete a Prime hoy",es_MX:"\u00danete a Amazon Prime hoy",fr_BE:"Rejoignez Prime aujourd'hui",fr_CA:"Abonnez-vous \u00e0 Prime aujourd'hui",fr_FR:"Rejoignez Prime aujourd'hui",he_IL:"\u05d4\u05e6\u05d8\u05e8\u05e3 \u05dc-Prime \u05d4\u05d9\u05d5\u05dd",hi_IN:"\u0906\u091c \u0939\u0940 Prime \u092e\u0947\u0902 \u0936\u093e\u092e\u093f\u0932 \u0939\u094b\u0902",
it_IT:"Iscriviti a Prime oggi",ja_JP:"\u30d7\u30e9\u30a4\u30e0\u306b\u767b\u9332",zh_CN:"\u7acb\u5373\u52a0\u5165Prime",kn_IN:"\u0c87\u0c82\u0ca6\u0cc7 Prime \u0cb8\u0cc7\u0cb0\u0cbf",ko_KR:"\uc9c0\uae08 Prime\uc5d0 \uac00\uc785\ud558\uc138\uc694",ml_IN:"\u0d07\u0d28\u0d4d\u0d28\u0d4d \u0d24\u0d28\u0d4d\u0d28\u0d46 Prime-\u0d7d \u0d1a\u0d47\u0d30\u0d42",mr_IN:"\u0906\u091c\u091a Prime \u092e\u0927\u094d\u092f\u0947 \u0938\u093e\u092e\u0940\u0932 \u0935\u094d\u0939\u093e",nl_BE:"Word vandaag lid van Prime",
nl_NL:"Word vandaag lid van Prime",pl_PL:"Do\u0142\u0105cz do Amazon Prime ju\u017c dzi\u015b",pt_BR:"Assine o Amazon Prime",pt_PT:"Subscrever o Amazon Prime hoje",sv_SE:"Bli Amazon Prime-medlem idag",ta_IN:"\u0b87\u0ba9\u0bcd\u0bb1\u0bc7 Prime-\u0b87\u0bb2\u0bcd \u0b9a\u0bc7\u0bb0\u0bc1\u0b99\u0bcd\u0b95\u0bb3\u0bcd",te_IN:"\u0c28\u0c47\u0c21\u0c47 Prime \u0c32\u0c4b \u0c1a\u0c47\u0c30\u0c02\u0c21\u0c3f",tr_TR:"Prime'a bug\u00fcn kat\u0131l",zh_TW:"\u7acb\u5373\u52a0\u5165Prime"},L=function(d){if(d=
null===d||void 0===d?void 0:d.getAttribute("data-csa-c-locale"))return d=d.replace(/-/g,"_"),d in z?d:void 0};B._operationNames=[];B.card=function(){return k.__awaiter(void 0,void 0,void 0,function(){return k.__generator(this,function(d){try{N("howToQualifyModal","",!1,600)}catch(b){p["default"].log("Error caught when attaching handlers to modal popup.")}return[2,K({cardRoot:x["default"].cardRoot,cardId:"slash-prime-hero-widget-desktop-card",painterId:"slash-prime-hero-banner-desktop-card",style:P})]})})}});
