'use strict';(function(k){var d=window.AmazonUIPageJS||window.P,t=d._namespace||d.attributeErrors,c=t?t("CheckoutCartPrefetchAsset",""):d;c.guardFatal?c.guardFatal(k)(c,window):c.execute(function(){k(c,window)})})(function(k,d,t){k.when("A").register("CartCheckoutPrefetch-GroceryPathHelper",function(c){return{getTangoDataPreinitUrl:function(){return null}}});"use strict";k.when("A").register("CartCheckoutPrefetch-PathHelper",function(c){var l={"/cart/haul":"/bazaar"};return{getTangoDataPreinitUrl:function(c,
e){c=c||{};a:{var h=d.location.pathname;for(g in l){var f=h.toLowerCase(),m=g.toLowerCase();if(-1!==f.indexOf(m)){var g=l[g];break a}}g=c.enableBusinessPreinit?"/amazon_business":""}g="/checkout/entry/cart"+g+"?isPreinit\x3d1\x26partialCheckoutCart\x3d1\x26pipelineType\x3dChewbacca\x26referrer\x3dcart";c.isEligibilityLogicDisabled&&(g+="\x26isEligibilityLogicDisabled\x3d1");e&&e.preInitiateExecutionId&&(g+="\x26preInitiateExecutionId\x3d"+encodeURIComponent(e.preInitiateExecutionId));e&&e.cartItemCount&&
(g+="\x26cartItemCount\x3d"+encodeURIComponent(e.cartItemCount));return g}}});"use strict";k.when("A","CartServerSetting","CartCheckoutPrefetch-DeviceAgnosticFunctions").register("CartCheckoutPrefetchDesktop",function(c,d,p){function e(){p.isTangoPreinitiateEligible()&&p.javaCheckoutPreinitiate()}var h=c.$,f=d.features.disableCheckoutPrefetchCaching;k.when("total-purchase-cost-prefetch-listeners").register("setupCartCheckoutPrefetch",function(){var d=!1,g=!1;f&&p.clearJavaPreinitValuesInBuyBox();
c.state.bind("checkout-url-migration-page-state",function(d,c){p.customerEligibilityChangeHandler(d,c,e)});c.on("sc:checkout-prefetch:start",function(){d=!0});c.on("sc:checkout-prefetch:complete",function(){d=!1;g&&h("#sc-buy-box form").submit()});c.on("tango:checkout:eligible:skipGurupaPrefetch",function(){d=!1;g&&h("#sc-buy-box form").submit()});h(document).delegate("#sc-buy-box form","submit",function(c){return d?(g=!0,c.preventDefault(),!1):!0});e();c.on("sc:checkout-prefetch",function(){e()});
c.on("affordability:clipCoupon:success",function(){p.clearJavaPreinitValuesInBuyBox();e()});c.on("shopwithpoints:preferenceUpdate:success",function(c){p.clearJavaPreinitValuesInBuyBox();e();p.logUECounter(c+"::TriggerPrefetchOnSuccess::Success",1)})})});"use strict";k.register("CartCheckoutPrefetch-window",function(){return{fetch:d.fetch?d.fetch.bind(d):t,TextDecoderStream:d.TextDecoderStream}});k.when("A","CartServerSetting","CartCheckoutPrefetch-PathHelper","CartCheckoutPrefetch-GroceryPathHelper",
"CartCheckoutPrefetch-window").register("CartCheckoutPrefetch-DeviceAgnosticFunctions",function(c,l,p,e,h){function f(b,a){c.trigger("sc:checkout-prefetch:start",{prefetchPromise:b});a&&(x=a)}function m(b){c.trigger("sc:checkout-prefetch:complete",b)}function g(){return!!document.getElementById("localmarket-full-cart")}function n(b,a){"undefined"!==typeof d.ue&&"undefined"!==typeof d.ue.count&&d.ue.count(b,a||1)}function k(b,a){d.ueLogError&&(a=a||{},a.logLevel=a.logLevel||"ERROR",a.attribution=a.attribution||
"CheckoutCartPrefetchAsset: Website \x3e Amazon Checkout Pipeline \x3e Others",a.message=a.message||"",d.ueLogError(b,a))}function D(){if(document.getElementById("bazaar-cart-container"))return"sc-bazaar-buy-box";if(g()){if(document.getElementById("sc-fresh-buy-box"))return"sc-fresh-buy-box";if(document.getElementById("sc-alm-buy-box"))return"sc-alm-buy-box"}return"sc-buy-box"}function v(){var b=document.getElementById(D());if(b&&(b=b.getElementsByTagName("form"),0!==b.length))return b[0]}function y(b){if(!v())return[];
for(var a=c.$("#"+D()+" input").serializeArray(),d={},q=0;q<a.length;q++)-1!==b.indexOf(a[q].name)&&(d[a[q].name]=a[q].value);return d}function u(b,a){var d=v();if(d){z(d,b);var c=document.createElement("input");c.setAttribute("type","hidden");c.setAttribute("value",a);c.setAttribute("name",b);d.appendChild(c)}}function z(b,a){if(b)for(b=b.querySelectorAll('input[name\x3d"'+a+'"]'),a=0;a<b.length;a++)b[a].parentNode.removeChild(b[a])}function A(){var b=v();b&&z(b,"preInitiateExecutionId")}function L(){if(r&&
d.caches){var b=r;r=null;d.caches.open("checkout-prefetch").then(function(a){n("prefetch_cache_clear_single",1);return a.delete("/checkout-prefetch/"+b)}).catch(function(a){k(a,{message:"Failed to clear prefetch from cache"})})}else r=null}function M(b,a,c,q,f,e){d.caches&&O&&(L(),r=b,d.caches.open("checkout-prefetch").then(function(c){n("prefetch_cache_store",1);return c.put("/checkout-prefetch/"+b,new Response(a))}).then(function(){"number"!==typeof e||isNaN(e)||n("prefetch_cache_store_time_ms",
(new Date).getTime()-e);u("isPrefetchedAvailable",c);q&&u("rrid",q);f&&u("view",f)}).catch(function(a){k(a,{message:"Failed to store encrypted prefetch response in cache"})}))}function E(b,a){a===x&&b&&!y(["preInitiateExecutionId"]).preInitiateExecutionId&&u("preInitiateExecutionId",b)}function P(b,a){a===x&&b&&n("prefetch_buybox_insert_time_ms",(new Date).getTime()-a);E(b,a)}function F(b,a,c,d,e){if(c=c||e||b&&b.executionHandle&&b.executionHandle.executionId)b&&b.payload&&b.token&&M(c,b.payload,
b.token,d,b.viewId,a),E(c,a)}function G(){H();I=setTimeout(A,3E5)}function H(){clearTimeout(I)}function J(b,a,c,d,e){if(h.fetch&&h.TextDecoderStream)return Q(b,a,c,d,e);K(b,a,c,d,e)}function B(b,a){if(b.done){if(""===a.dataSoFar.trim())return n(a.prefetchType+"prefetch_ajax_streaming_nodata",1),null;try{var c=JSON.parse(a.dataSoFar);l.features.enableHeaderExecutionIdFallback&&a.headerExecutionId&&c&&(c.headerExecutionId=a.headerExecutionId);a.successHandler&&a.successHandler(c,a.cartInitiateId,a.headerExecutionId,
a.headerRequestId,a.requestedExecutionId);n(a.prefetchType+"prefetch_ajax_streaming_success",1);return c}catch(N){return n(a.prefetchType+"prefetch_ajax_streaming_parse_failure",1),null}}a.dataSoFar+=b.value;try{var d=JSON.parse(a.dataSoFar)}catch(N){return a.reader.read().then(function(b){return B(b,a)})}l.features.enableHeaderExecutionIdFallback&&a.headerExecutionId&&d&&(d.headerExecutionId=a.headerExecutionId);a.successHandler&&a.successHandler(d,a.cartInitiateId,a.headerExecutionId,a.headerRequestId,
a.requestedExecutionId);n(a.prefetchType+"prefetch_ajax_streaming_success",1);return d}function Q(b,a,c,d,e){var g={"x-amzn-tiertwo":"yes"};"javaCheckoutPreInitiate:"===a&&(g["x-amz-checkout-transition"]="ajax");var l=null,p=null;b=h.fetch(b,{headers:g,cache:"no-store"}).then(function(b){l=b.headers.get("x-amz-checkout-executionid");p=b.headers.get("x-amz-checkout-requestid");P(l,d);b=b.body.pipeThrough(new h.TextDecoderStream).getReader();var f={dataSoFar:"",reader:b,headerExecutionId:l,headerRequestId:p,
requestedExecutionId:e,prefetchType:a,successHandler:c,cartInitiateId:d};return b.read().then(function(a){return B(a,f)})}).catch(function(b){k(b,{message:"streamJSONUsingFetch failed"});n(a+"prefetch_ajax_streaming_error",1);return null}).then(function(a){m(a);return a});f(b,d);return b}function K(b,a,d,e,g){var h={"x-amzn-tiertwo":"yes"};"javaCheckoutPreInitiate:"===a&&(h["x-amz-checkout-transition"]="ajax");b=c.$.ajax(b.toString(),{cache:!1,headers:h,success:function(b,c,f){c=f.getResponseHeader("x-amz-checkout-executionid");
f=f.getResponseHeader("x-amz-checkout-requestid");l.features.enableHeaderExecutionIdFallback&&c&&b&&(b.headerExecutionId=c);d&&d(b,e,c,f,g);n(a+"prefetch_ajax_jquery_success",1);m(b);return b},error:function(){n(a+"prefetch_ajax_jquery_error",1);m();return null}});f(b,e)}var w=!1,x,r,I,C=!1,O=l.features.enableCheckoutContentPrefetchCache;(function(){d.caches?d.caches.open("checkout-prefetch").then(function(b){return b.keys().then(function(a){0<a.length&&n("prefetch_cache_clear_all",a.length);return Promise.all(a.map(function(a){return b.delete(a)}))})}).catch(function(b){k(b,
{message:"Failed to clear all prefetch entries from cache"})}).then(function(){r=null}):r=null})();return{streamJSONPrefetchRequest:J,fireAndForgetPrefetchRequest:function(b,a){K(b,a,t,t)},getJavaCheckoutPreinitiateIdentifier:function(){return"javaCheckoutPreInitiate:"},executionIdSuccessHandler:function(b,a,c){(b=c||b&&b.executionHandle&&b.executionHandle.executionId)&&u("preInitiateExecutionId",b)},javaCheckoutPreintiateSuccessHandler:F,javaCheckoutPreinitiate:function(){var b=(new Date).getTime();
G();var a=y(["preInitiateExecutionId","cartItemCount"]),c=a.preInitiateExecutionId;a=g()?e.getTangoDataPreinitUrl(l.features.isEligibilityLogicDisabled,a):p.getTangoDataPreinitUrl(l.features,a);a&&J(a,"javaCheckoutPreInitiate:",F,b,c)},isTangoPreinitiateEligible:function(){var b=document.getElementById("checkout-url-server-migration-status");return(C=b&&"true"===b.value)&&!w},customerEligibilityChangeHandler:function(b,a,c){a.checkoutUrl&&C&&(w=!b.checkoutUrl)&&(A(),c())},clearInvalidationTimer:H,
setInvalidationTimeout:G,isAjaxCallBlocking:function(){return w},isJavaCheckoutServerStateEnabled:function(){return C},setAjaxBlockingFlag:function(b){w=b},getBuyBoxForm:v,clearValueInBuyBox:z,clearJavaPreinitValuesInBuyBox:A,insertValueInBuyBox:u,getBuyBoxParameters:y,logUECounter:n,pumpChunk:B}});"use strict";k.when("A","BYGServerSetting").register("BeforeYouCheckoutPagePrefetch",function(c,l){function k(h){e("byc_prefetch_ajax_call_initiate",1);c.$.ajax(h,{success:function(){e("prefetch_byc_ajax_jquery_success",
1)},error:function(c){e("prefetch_byc_ajax_jquery_error",1);d.ueLogError&&d.ueLogError(c,{logLevel:"ERROR",attribution:"CheckoutCartPrefetchAsset: Website \x3e Amazon Checkout Pipeline \x3e Others",message:"byc_firePrefetchRequest failed"})}})}function e(c,e){"undefined"!==typeof d.ue&&"undefined"!==typeof d.ue.count&&d.ue.count(c,e||1)}c.on("sc:byg:recs:added",function(h){e("byg_prefetch_converged_js_invoked",1);var f=c.$("a[name\x3dsc-byc-ptc-button]"),m=c.state("bygPageState").tangoUrl;f.attr("href")===
m&&h.isTurbo||!l.features||!l.features.enableBYGPrefetch||(h=(new Date).getTime(),f=new URL("/gp/cart/checkout-prefetch.html",d.location.origin),f.searchParams.set("checkAuthentication","1"),f.searchParams.set("checkDefaults","1"),f.searchParams.set("cartInitiateId",h),(m=(new URL(c.$("a[name\x3dsc-byc-ptc-button]").attr("href"),d.location.origin)).searchParams.get("partialCheckoutCart"))&&f.searchParams.set("partialCheckoutCart",m),k(f.href),f=c.$("a[name\x3dsc-byc-ptc-button]"),m=c.state("bygPageState").ingressUrl,
m=new URL(m,d.location.origin),m.searchParams.has("cartInitiateId")&&(m.searchParams.set("cartInitiateId",h),f.attr("href",m.pathname+m.search)))})})});