(function(h){var p=window.AmazonUIPageJS||window.P,k=p._namespace||p.attributeErrors,d=k?k("GiftRegistryComponentsAssets@common",""):p;d.guardFatal?d.guardFatal(h)(d,window):d.execute(function(){h(d,window)})})(function(h,p,k){h.when("A","ready").register("gr-ajax-utils",function(d){var f=d.$;return{getCsrfToken:function(){var c=f("#generic-registry-anticsrf-token")[0].content;return c?c:f("input[name\x3d__token_]").val()}}});"use strict";h.when("A","ready").register("gr-amazonapi-utils",function(d){function f(n,
a,b){this.csrfToken=n;this.endpoint=a;this.marketplaceId=b}function c(n,a,b,c){this.gifterName=n;this.message=a;this.amount=b;this.currencyCode=c}function b(a,b,c,e,g,d,f,m,l,h){this.requestDetails=a;this.asin=b;this.cartItemId=c;this.offerListingId=e;this.registryId=g;this.registryItemId=d;this.quantity=f!==k?parseInt(f,10):1;this.hasGiftOptions=h?!1:m;this.customizationToken=l;this.giftCard=h}function a(a,b){return"https://"+a.endpoint+"/api/marketplaces/"+a.marketplaceId+"/cart/carts/retail/items"+
(b?"?ref_\x3d"+b:"")}function e(a){var b={};Object.assign(b,a.giftCard&&{giftCardMetadata:{designAsin:a.asin,from:a.giftCard.gifterName,message:a.giftCard.message,amount:{amount:parseFloat(a.giftCard.amount).toFixed(2),currencyCode:a.giftCard.currencyCode,displayString:""},registryId:a.registryId,registryItemId:a.registryItemId,type:"GROUP"}},a.hasGiftOptions&&{giftOptions:{includeGiftReceipt:!0}},a.customizationToken&&{customizationToken:a.customizationToken},a.registryItemId&&{listPurchaseAttribution:{listAttributionId:a.registryId,
itemAttributionId:a.registryItemId}});return JSON.stringify({items:[{asin:a.asin,offerListingId:a.offerListingId,quantity:a.quantity,additionalParameters:b}]})}function g(a){return a&&l.cartCountResponseType===a.type&&"items"in a.entity}var m=d.$,l={addToCartResponseType:"cart.add-items/v1",cartCountResponseType:"cart.count/v1",requestMIMEType:'application/vnd.com.amazon.api+json; type\x3d"cart.add-items.request/v1"',responseMIMEType:'application/vnd.com.amazon.api+json; type\x3d"cart.add-items/v1"'};
return{cartRequest:function(a,c,e,g,d,f,m,l,h,k){return new b(a,c,e,g,d,f,m,l,h,k)},giftCard:function(a,b,e,g){return new c(a,b,e,g)},requestDetails:function(a,b,c){return new f(a,b,c)},addToCart:function(b,c,f,k){var n=b.requestDetails.csrfToken;c=a(b.requestDetails,c);m.ajax({url:c,xhrFields:{withCredentials:!0},type:"POST",headers:{"Content-Type":l.requestMIMEType,Accept:l.responseMIMEType,"Accept-Language":"en-US","x-api-csrf-token":n,"x-amzn-encrypted-slate-token":d.$("meta[name\x3d'encrypted-slate-token']").prop("content")},
data:e(b),success:function(a){l.addToCartResponseType===a.type&&"items"in a.entity&&0<a.entity.items.length&&g(a.entity.count)?function(){var b={cartTotalCount:a.entity.count.entity.items,itemsAdded:a.entity.items};f&&f(b);h.when("nav.setCartCount").execute(function(a){a(b.cartTotalCount)});h.when("mash").execute(function(a){a.cart.didUpdate({newCartQuantity:b.cartTotalCount})})}():k&&k(a)},error:function(a,b,c,e){k&&k(a,b,c,e)}})},modifyItemInCart:function(b,c,e,g){var f=b.requestDetails.csrfToken;
c=a(b.requestDetails,c);m.ajax({url:c,xhrFields:{withCredentials:!0},type:"PUT",headers:{"Content-Type":'application/vnd.com.amazon.api+json; type\x3d"cart.modify-items.request/v1"',Accept:'application/vnd.com.amazon.api+json; type\x3d"cart.modify-items/v1"',"Accept-Language":"en-US","x-api-csrf-token":f,"x-amzn-encrypted-slate-token":d.$("meta[name\x3d'encrypted-slate-token']").prop("content")},data:JSON.stringify({items:[{id:b.cartItemId,quantity:b.quantity,unitOfMeasureQuantity:{value:b.quantity,
unitOfMeasure:{dimension:"COUNT",unit:"UNITS"}}}]}),success:function(a){var b={cartTotalCount:a.entity.count.entity.items};e&&e(b);h.when("nav.setCartCount").execute(function(a){a(b.cartTotalCount)});h.when("mash").execute(function(a){a.cart.didUpdate({newCartQuantity:b.cartTotalCount})})},error:function(a,b,c,e){g&&g(a,b,c,e)}})}}});"use strict";h.when("A","ready").register("gr-authentication-utils",function(d){return{isAuthenticated:function(f,c){d.get("/registries/isAuthenticated",{cache:!1,success:function(b,
a,e){"true"===b.result.authenticated?f():c()},error:function(b,a,e){c(b,a,e)}})}}});"use strict";h.when("A","ready").register("gr-banner-utils",function(d){return{showBanner:function(d,c){a:{var b=decodeURIComponent(document.cookie).split(";");for(var a=0;a<b.length;a++){var e=b[a].trim();if(0===e.indexOf("bannerExpires\x3d")){b=e.substring(14,e.length);break a}}b=null}b=Date.parse(b);!isNaN(b)&&b<Date.now()||(d.show(),d=new Date,d.setTime(d.getTime()+c),document.cookie="bannerExpires\x3d"+d.toUTCString()+
"; path\x3d/")}}});"use strict";h.when("A","a-toggle-button","ready").register("gr-button-utils",function(d,f){var c=d.$;return{initializeToggleButton:function(b,a){c(b).click(function(){if(!a||a.isEnabled()){var c=f(b);c.isSelected()?c.setUnselected():c.setSelected()}})}}});"use strict";h.when("A","ready").register("gr-follow-list-utils",function(d){var f={WEDDING:"WEDDING",BABY:"BABY",EVENT:"eventRegistry"};return{ListType:f,getFollowId:function(c,b){return(f[c.toUpperCase()]||f.EVENT)+":"+b}}});
"use strict";h.when("A","ready").register("gr-html-utils",function(d){var f=d.$;return{renderChangeover:function(c,b){b||(b=document);f(b).find(c).css("display","flex")}}});"use strict";h.when("A","ready").register("gr-js-utils",function(d){function f(c,b){c()?b&&b():setTimeout(f,100,c,b)}return{cleanAssign:function(c,b){var a=!0,e=!1,g=k;try{for(var d=Object.getOwnPropertyNames(c)[Symbol.iterator](),f;!(a=(f=d.next()).done);a=!0)delete c[f.value]}catch(n){e=!0,g=n}finally{try{!a&&d.return&&d.return()}finally{if(e)throw g;
}}Object.assign(c,b)},waitFor:f}});"use strict";h.when("A","gr-ajax-utils","ready").register("gr-nosgur-utils",function(d,f){return{ItemType:{GiftCardFund:"GIFT_CARD_FUND",GeneralAmazonProduct:"GENERAL_AMAZON_PRODUCT"},addToRegistry:function(c){var b="/registries/state/registries/type/"+c.eventType+"/id/"+c.registryId+"/items";c.refTag&&(b+="?ref_\x3d"+c.refTag);d.post(b,{accepts:"application/json",contentType:"application/json",headers:{"anti-csrftoken-a2z":c.csrfToken},paramsFormat:"json",params:c.atrAjaxRequest,
success:function(a,b,g){c.successCallback&&c.successCallback(a)},error:function(a,b,g){c.errorCallback&&c.errorCallback(a)}})},markAsPurchased:function(c){var b="/registries/state/registries/type/"+c.eventType+"/id/"+c.registryId+"/items/"+c.itemId+"/reservations";c.refTag&&(b+="?ref_\x3d"+c.refTag);var a={reservedQuantity:c.reservedQuantity,returnToUrl:c.returnToUrl};d.post(b,{accepts:"application/json",contentType:"application/json",headers:{"anti-csrftoken-a2z":f.getCsrfToken()},paramsFormat:"json",
params:a,success:function(a,b,d){c.successCallback&&c.successCallback(a)},error:function(a,b,d){c.errorCallback&&c.errorCallback(a)}})}}});"use strict";h.when("A","ready").register("gr-ref-tag-utils",function(d){return{formatRefTag:function(d,c,b){return b?"gr-"+d+"-"+c+"-"+b:""}}});"use strict";h.when("A","a-modal-framework","a-modal-framework-constants","gr-ui-utils","ready").register("gr-side-sheet",function(d,f,c,b){function a(a){var b="#gr-side-sheet-id__"+a.name;d.on("a:modalFramework:"+a.name+
":presented",function(a){g(b).removeClass(m.hideSideSheet)});d.on("a:modalFramework:"+a.name+":beforeDismiss",function(a){g(b).addClass(m.hideSideSheet);setTimeout(function(){a.promiseToDismiss.resolve()},500)});d.on("a:modalFramework:"+a.name+":dismissed",function(c){h[a.name]&&g(b+" ."+m.sideSheetContents).empty()});d.on("a:modalFramework:"+a.name+":contentUpdated",function(b){if(a.onContentLoaded)a.onContentLoaded()})}function e(a){h[a]&&h[a].dismiss()}var g=d.$,m={sideSheet:"gr-side-sheet",sideSheetHeading:"gr-side-sheet__heading",
sideSheetContents:"gr-side-sheet__contents",sideSheetCloseIcon:"gr-side-sheet__close-icon",hideSideSheet:"gr-side-sheet--hide"},h={};g(document).delegate("."+m.sideSheetCloseIcon,"click",function(a){a=g(a.currentTarget).parents("."+m.sideSheet).first().data("name");e(a)});return{close:e,open:function(e){var l="gr-side-sheet-id__"+e.name,k="#"+l;if(h[e.name])d.get(e.ajaxUrl,{success:function(a,b,c){g(k+" ."+m.sideSheetContents).html(a);if(e.onContentLoaded)e.onContentLoaded()}});else{var n={type:"ajax",
source:e.ajaxUrl};l=g("\x3cdiv\x3e",{id:l,class:m.sideSheet});l.data("name",e.name);if(e.heading){var p=g("\x3cdiv\x3e",{class:m.sideSheetHeading+" a-size-base-plus a-text-bold"});p.html(e.heading);l.append(p)}l.append(g("\x3cdiv\x3e",{class:m.sideSheetContents+" "+c.CONTENT_WRAPPER_CLASS,width:e.width?e.width:"800px"}));l.append(b.createCloseIcon(m.sideSheetCloseIcon));g("body").append(l);h[e.name]=new f(g(k),n,{hasDismissAnimation:!0,name:e.name});a(e)}h[e.name].present()}}});"use strict";h.when("A",
"ready").register("gr-state-managers",function(d){function f(b,a){var c={},g=a;c.onboard=function(a){d.on(b,function(){a[g]()})};c.setState=function(a){g=a;d.trigger(b)};c.getState=function(){return g};c.getEventName=function(){return b};return c}var c=d.$;return{CooldownManager:function(b){var a={},e=f(b,"enabled");a.onboard=function(a,b){var c={};c.enabled=a;c.disabled=b;e.onboard(c)};a.enable=function(){e.setState("enabled")};a.disable=function(){e.setState("disabled")};a.delegate=function(b,e,
d){c(document).delegate(b,e,function(b){a.isEnabled()&&d(b)})};a.on=function(b,c){d.on(b,function(){a.isEnabled()&&c.apply(k,arguments)})};a.declarative=function(b,c,e){d.declarative(b,c,function(){a.isEnabled()&&e.apply(k,arguments)})};a.getEventName=e.getEventName;a.isEnabled=function(){return"enabled"===e.getState()};return a}}});"use strict";h.when("A","a-modal","gr-side-sheet","ready").register("gr-ui-modal-handler",function(d,f,c){var b=d.$;return{closeModal:function(a,e,d){d?(a=f.get(a))&&
a.hide():c.close(a);e&&b(e).css("display","flex")}}});"use strict";h.when("A","a-button","a-switch","ready").register("gr-ui-utils",function(d,f,c){var b=d.$;return{enableInteractiveElements:function(a,e){e.forEach(function(e){f(e).isEmpty()?c.getSwitch(b(e))&&c.getSwitch(b(e)).enabled(a):a?b(e+" :input").removeProp("disabled"):b(e+" :input").prop("disabled",!0)})},isElementHidden:function(a){return b(a).attr("class").includes("aok-hidden")},hideElement:function(a){a.addClass("aok-hidden")},showElement:function(a){a.removeClass("aok-hidden")},
applyClass:function(a,c,d){b(a).each(function(){d(b(this))?b(this).addClass(c):b(this).removeClass(c)})},changeButtonText:function(a,b){a=f(a);a.isEmpty()||a.text(b)},scrollToElement:function(a,c){var e=b(p);c&&(e=b(c));e.animate({scrollTop:b(a).offset().top})},onVisibilityChange:function(a,b){a&&(new IntersectionObserver(function(a,c){(a=0<a[0].intersectionRatio)&&b(a)})).observe(a)},createCloseIcon:function(a){return b("\x3cbutton\x3e",{class:"gr-close-icon "+a,type:"button","aria-label":"close"})}}});
"use strict";h.when("A","ready").register("wr-base-temp",function(d){var f=d.$,c={submitError:function(b,a,c,d){b.error&&b.error(b,a,c,d)},submitSuccess:function(b,a,c,d){b.success&&b.success(b,a,c,d)},getCsrfToken:function(){return d.state("token")?d.state("token").value:null}};return{ajax:function(b,a){var e=f.extend(!0,{},a);b||(b="");var g={};a.params&&(g=a.params);a.queryParams&&(b+="?token\x3d"+encodeURIComponent(c.getCsrfToken())+"\x26"+f.param(a.queryParams));a.method&&"GET"!==a.method.toUpperCase()&&
"json"!==a.paramsFormat&&(g.token=c.getCsrfToken());e.params=g;e.success=function(b,d,e){c.submitSuccess(a,d,e,b)};e.error=function(b,d,e){c.submitError(a,d,b,e)};return d.ajax(b,e)},getCsrfToken:function(){return c.getCsrfToken()},DEFAULT_TIME_OUT:1E4}})});
/* ******** */
(function(h){var n=window.AmazonUIPageJS||window.P,q=n._namespace||n.attributeErrors,g=q?q("GenericGiftRegistryAssets@common",""):n;g.guardFatal?g.guardFatal(h)(g,window):g.execute(function(){h(g,window)})})(function(h,n,q){h.when("A","ready").register("gr-amazonapi-ajax",function(g){function f(a,b,c,p,k,e,f){a={items:[{asin:a,quantity:1,additionalParameters:{giftCardMetadata:{designAsin:a,from:b,message:c,amount:{amount:parseFloat(p).toFixed(2),currencyCode:f,displayString:""},registryId:k,registryItemId:e,
type:"GROUP"},listPurchaseAttribution:{listAttributionId:k,itemAttributionId:e}}}]};return JSON.stringify(a)}function b(b){return b&&a.cartCountResponseType===b.type&&"items"in b.entity}var e=g.$,a={addToCartResponseType:"cart.add-items/v1",cartCountResponseType:"cart.count/v1",requestMIMEType:'application/vnd.com.amazon.api+json; type\x3d"cart.add-items.request/v1"',responseMIMEType:'application/vnd.com.amazon.api+json; type\x3d"cart.add-items/v1"'};return{addContribution:function(d,l,c,p,k,m,t,
n,q,r){e.ajax({url:"https://"+r.ajaxEndpoint+"/api/marketplaces/"+r.marketplaceId+"/cart/carts/retail/items?ref\x3d"+q,xhrFields:{withCredentials:!0},type:"POST",headers:{"Content-Type":a.requestMIMEType,Accept:a.responseMIMEType,"Accept-Language":"en-US","x-api-csrf-token":r.csrfToken,"x-amzn-encrypted-slate-token":g.$('meta[name\x3d"encrypted-slate-token"]').prop("content")},data:f(d,l,c,p,k,m,r.currencyOfPreference),success:function(c){if(a.addToCartResponseType===c.type&&"items"in c.entity&&0<
c.entity.items.length&&b(c.entity.count)){t(c);var p=c.entity.count.entity.items;h.when("nav.setCartCount").execute(function(c){c(p)});h.when("mash").execute(function(c){c.cart.didUpdate({newCartQuantity:p})})}else n(c)},error:function(c,a,b,p){n(c,a,b,p)}})}}});h.when("A","gr-ajax-utils","ready").register("gr-base-ajax",function(g,f){var b=g.$,e={submitError:function(a,b,e,c){a.error&&a.error(a,b,e,c)},submitSuccess:function(a,b,e,c){a.success&&a.success(a,b,e,c)},getCsrfToken:function(){return b("input[name\x3d__token_]").val()}};
return{ajax:function(a,d){var l=b.extend(!0,{},d);a||(a="");var c={};d.params&&(c=d.params);d.useShoppingPortalCsrfToken?l.headers={"anti-csrftoken-a2z":f.getCsrfToken()}:d.method&&"GET"!==d.method.toUpperCase()&&!c.token&&(c.token=e.getCsrfToken());l.params=c;l.success=function(c,a,b){e.submitSuccess(d,a,b,c)};l.error=function(c,a,b){e.submitError(d,a,c,b)};return g.ajax(a,l)},redirectHandler:function(a){a&&a.http&&a.http.response&&(response=JSON.parse(a.http.response),response.redirectURL&&n.location.assign(response.redirectURL))},
DEFAULT_TIME_OUT:1E4}});h.when("A","ready").register("gr-validate",function(g){var f=/^[1-9]\d*$/;return{name:function(b){return!!b&&0<b.trim().length&&60>=b.trim().length},searchUrl:function(b){return!!b&&0<b.trim().length},eventDate:function(b,e){var a=new Date;a.setHours(0,0,0,0);return b&&(b>=a||e&&b.getTime()===e.getTime())},eventState:function(b){return!!b},eventOwnerName:function(b){return!!b&&120>=b.length},registryName:function(b){return!!b&&80>=b.length},eventAddressId:function(b){return!!b},
guestCount:function(b){return!b||f.test(b)}}});h.when("A","ready").register("gr-utils",function(g){function f(c,a){c()?a&&a():setTimeout(f,100,c,a)}var b=g.$,e={profilePhotoDelete:{url:"/registries/photo/delete",refTagSegment:"ajx_dpp"},profilePhotoUpload:{url:"/registries/photo/upload",refTagSegment:"ajx_ppu"},bannerPhotoUploadAjax:{url:"/registries/photo/update",refTagSegment:"ajx_bpu"},bannerPhotoDeleteAjax:{url:"/registries/photo/delete",refTagSegment:"ajx_bpd"},modalProfilePhotoUpload:{url:"/registries/profile-photo-upload",
refTagSegment:"ajx_ppumdl"},modalBannerPhotoUpload:{url:"/registries/banner-photo-upload",refTagSegment:"ajx_bpumdl"}},a=null,d=g.state("localizedCalendarStrings"),l={formatDate:function(c,a){var b=c.dayOfMonth,p=c.month.toLowerCase().substring(0,3);c=c.year;switch(a){case "MM DD, YYYY":return p+" "+b+", "+c}return""},convertToDate:function(c){var a=d["date-format-pattern"];var b=c.split(/[/-]/);if(2<b.length)switch(a){case "dd/mm/yyyy":a=b[0];c=b[1];b=b[2];break;case "yyyy/mm/dd":a=b[2];c=b[1];b=
b[0];break;case "yyyy-mm-dd":a=b[2];c=b[1];b=b[0];break;default:a=b[1],c=b[0],b=b[2]}else return null;return new Date(b,c-1,a)},extractEventDateForRegistry:function(a){if(a.eventDate){var b=a.eventDate;a.eventYear=b.getFullYear();a.eventMonth=b.getMonth()+1;a.eventDay=b.getDate();return a}},getCsrfToken:function(){return b("input[name\x3d__token_]").val()},componentRefTagKey:{banner:"bnr"},isBrowserIeVersionLessThan:function(c){if(7>c||10<c)return!1;a||(a=b("html"));return a.hasClass("a-lt-ie"+c)},
isBrowserIe10:function(){a||(a=b("html"));return a.hasClass("gr-ie10")},getPageRefTag:function(){return(new URLSearchParams(n.location.search)).get("ref_")},getUrl:function(a,b,d,f){a=e[a];if("undefined"!==typeof a){b&&"object"===typeof b||(b={});a=a.url;d=-1===a.indexOf("?")?"?":"\x26";for(var c in b)b.hasOwnProperty(c)&&(-1!==a.indexOf("{"+c+"}")?a=a.replace("{"+c+"}",encodeURIComponent(b[c])):(a+=d+c+"\x3d"+encodeURIComponent(b[c]),d="\x26"));return a}},getAlertHtml:function(a,b,d){return"boolean"===
typeof d&&d?'\x3cdiv class\x3d"a-box a-alert a-alert-{type} {inlineClass}"\x3e\x3cdiv class\x3d"a-box-inner a-alert-container"\x3e\x3ci class\x3d"a-icon a-icon-alert"\x3e\x3c/i\x3e\x3cdiv class\x3d"a-alert-content"\x3e{message}\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e'.replace("{type}","inline-"+a).replace("{message}",b).replace("{inlineClass}","a-alert-inline"):'\x3cdiv class\x3d"a-box a-alert a-alert-{type} {inlineClass}"\x3e\x3cdiv class\x3d"a-box-inner a-alert-container"\x3e\x3ci class\x3d"a-icon a-icon-alert"\x3e\x3c/i\x3e\x3cdiv class\x3d"a-alert-content"\x3e{message}\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e'.replace("{type}",
a).replace("{message}",b).replace("{inlineClass}","")},getAjaxFailAlertHtml:function(a,b){return l.getAlertHtml("error",(a?a:null)+(b?" "+b:""))},getLoadingSpinnerHtml:function(a){return a?'\x3cdiv class\x3d"a-spinner-wrapper gr-spinner-gray"\x3e\x3cspan class\x3d"a-spinner a-spinner-medium"\x3e\x3c/span\x3e\x3c/div\x3e':'\x3cdiv class\x3d"a-spinner-wrapper gr-spinner"\x3e\x3cspan class\x3d"a-spinner a-spinner-medium"\x3e\x3c/span\x3e\x3c/div\x3e'},getLMSString:function(a){return b("#lmsStrings").data(a)},
isAuthenticated:function(a,b){g.get("/registries/isAuthenticated",{cache:!1,success:function(c,d,e){c.result?a():b()},error:function(a,c,d){b(a,c,d)}})},isWithinRange:function(a,b,d,e){if(Number.isNaN(a))return!1;a=Number.parseFloat(a);return e?a>=b&&a<=d:a>b&&a<d},decodeHtml:function(a){return b("\x3cdiv\x3e").html(a).text()},copyTextToClipboard:function(a){var b=document.createElement("textarea");b.value=a;b.setAttribute("readonly","");b.style={position:"absolute",left:"-9999px"};document.body.appendChild(b);
b.select();document.execCommand("copy");document.body.removeChild(b)},waitFor:f};return l});"use strict";h.when("A","a-button","a-switch","ready").register("gr-old-ui-utils",function(g,f,b){var e=g.$;return{enableInteractiveElements:function(a,d){d.forEach(function(d){f(d).isEmpty()?b.getSwitch(e(d))&&b.getSwitch(e(d)).enabled(a):a?e(d+" :input").removeProp("disabled"):e(d+" :input").prop("disabled",!0)})},isElementHidden:function(a){return e(a).attr("class").includes("aok-hidden")},hideElement:function(a){a.addClass("aok-hidden")},
showElement:function(a){a.removeClass("aok-hidden")},applyClass:function(a,b,f){e(a).each(function(){f(e(this))?e(this).addClass(b):e(this).removeClass(b)})},changeButtonText:function(a,b){a=f(a);a.isEmpty()||a.text(b)},scrollToElement:function(a){a=e(a);e(n).scrollTop(a.position().top)},onVisibilityChange:function(a,b){a&&(new IntersectionObserver(function(a,c){(a=0<a[0].intersectionRatio)&&b(a)})).observe(a)}}});h.when("A","ready").register("gr-url-utils",function(g){return{createProductDetailPageLink:function(f,
b,e,a){var d="";e&&(d+="colid\x3d"+e);a&&(e="coliid\x3d"+a,d+=d?"\x26"+e:e);b&&(b="ref_\x3d"+b,d+=d?"\x26"+b:b);return"/dp/"+f+"?"+d+"\x26th\x3d1\x26psc\x3d1"},updateUrlQueryParams:function(f,b,e){f=new URL(f);f.searchParams.set(b,e);n.history.replaceState&&n.history.replaceState({},document.title,f)}}});h.when("A","ready").register("gr-event-utils",function(g){var f={imageLoadSucceed:null,imageLoadFailed:null,imageLoadStarted:null,imageLoadEnded:null,bannerImageLoadSuccess:null},b=[],e={},a={eventTrigger:function(d,
g,c){var l,k;if(null!==(k=/([^:\s]+)(\s*:\s*([^,\s]+))?/g.exec(d)))d=k[1],k[3]&&(l=k[1]+":"+k[3]);else return a;if("undefined"===typeof f[d])return a;c||(c=this);var m;if(l){if(f[l]){var h=f[l].length;for(m=0;m<h;m++)k=f[l][m],b[k]&&b[k].apply(c,g)}e[l]={params:g,context:c}}if(f[d])for(h=f[d].length,m=0;m<h;m++)k=f[d][m],b[k]&&b[k].apply(c,g);return a},eventListen:function(d,g,c){if(!d||"function"!==typeof g)return a;for(var l=/([^:,\s]+)(\s*:\s*([^,\s]+))?/g,k=[],m;null!==(m=l.exec(d));)"undefined"!==
typeof f[m[1]]&&k.push({event:m[1],name:m[3]});d=k.length;if(!d)return a;l=b.push(g)-1;for(m=0;m<d;m++)if(k[m].name){var h=k[m].event+":"+k[m].name;f[h]||(f[h]=[]);f[h].push(l);c&&"object"===typeof e[h]&&g.apply(e[h].context?e[h].context:this,e[h].params)}else h=k[m].event,f[h]||(f[h]=[]),f[h].push(l);return a}};return a});h.when("A","ready").register("message-render",function(g){var f=g.$;return{showChangeOver:function(b,e,a){b=f(b);b.stop(!0,!0);b.find("strong").text(e);b.is(":visible")||b.fadeIn(400);
b.delay(2E3).fadeOut(800,function(){a&&a()})},closeChangeOver:function(b){f(b).hide()}}});h.when("A","a-calendar-renderer","ready").register("calendar-renderer-localized",function(g,f){if(!g.state("localizedCalendarStrings"))return new f({monthNames:"January February March April May June July August September October November December".split(" "),dayNamesShort:"Sun Mon Tue Wed Thu Fri Sat".split(" "),firstDay:0,currentFormat:"{{month}} {{year}}",genericStatus:"Show {{month}} {{year}}",dateFormat:"mm/dd/yyyy",
dateFormatDescription:"Date with format m m/d d/y y y y"});var b=g.state("localizedCalendarStrings");g={monthNames:function(){for(var e=[],a=0;12>a;a++)e.push(b["month-name"+a]);return e}(),dayNamesShort:function(){for(var e=[],a=0;7>a;a++)e.push(b["short-day-name"+a]);return e}(),firstDay:b["first-day-of-week"]?parseInt(b["first-day-of-week"]):0,currentFormat:b["calendar-header"],genericStatus:b["calendar-generic-status-prefix"]+" "+b["calendar-header"],dateFormat:b["date-format-pattern"],dateFormatDescription:b["calendar-date-format-description"]};
return new f(g)});h.when("A","ready").register("gr-clickstream",function(g){return{functional:function(f){n.ue&&uet("fn",f)},load:function(f){n.ue&&uex("ld",f)},logCsmCounter:function(f){n.ue&&n.ue.count&&n.ue.count(f,1)}}});h.when("A","ready").register("gr-old-state-managers",function(g){function f(b,a){var d={},e=a;d.onboard=function(a){g.on(b,function(){a[e]()})};d.setState=function(a){e=a;g.trigger(b)};d.getState=function(){return e};d.getEventName=function(){return b};return d}var b=g.$;return{CooldownManager:function(e){var a=
{},d=f(e,"enabled");a.onboard=function(a,b){var c={};c.enabled=a;c.disabled=b;d.onboard(c)};a.enable=function(){d.setState("enabled")};a.disable=function(){d.setState("disabled")};a.delegate=function(d,c,e){b(document).delegate(d,c,function(b){a.isEnabled()&&e(b)})};a.getEventName=d.getEventName;a.isEnabled=function(){return"enabled"===d.getState()};return a}}});h.when("A","gr-clickstream","ready").register("gr-form-utils",function(g,f){var b=g.$,e=function(a){"undefined"!==typeof a&&f.logCsmCounter(a)};
return{logTextInputInteraction:function(a,b){a.each(function(a){var c=a.attr("type");if("text"===c||"number"===c)a.on(b,function(b){""!==a.val()&&e(a.attr("name"))})})},logDropdownInteraction:function(a){g.on(a,function(a){e(a.name)})},logCalendarInteraction:function(a,d,f){a.on(f,function(a){""!==b(d).val()&&e("eventDate")})}}})});
/* ******** */
(function(e){var b=window.AmazonUIPageJS||window.P,f=b._namespace||b.attributeErrors,a=f?f("GenericGiftRegistryAssets@component_subnav",""):b;a.guardFatal?a.guardFatal(e)(a,window):a.execute(function(){e(a,window)})})(function(e,b,f){e.when("A","ready").register("nav-menu",function(a){var c=a.$,e=function(){var d=a.state("subnavState");if("private"===d.privacyStatus){var b=c("#gr-subnav-share");a.declarative.remove(b,"ssf-share-icon");a.declarative.create(b,"share-icon-private")}else b=c("#gr-subnav-share"),
d={url:d.canonicalShareUrl,title:d.shareDescription,emailSubject:d.shareTitle,t:{taf_share_bottom_sheet_title:d.shareTitle,taf_copy_url_changeover:d.copyUrlChangeover},type:"popover",refId:"ggr-subnav-share",popoverDistance:-10},a.declarative.remove(b,"share-icon-private"),a.declarative.create(b,"ssf-share-icon",d)};e();a.state.bind("subnavState",function(b,a){a.privacyStatus&&e()});var b=function(){c(".gr-subnav__group--secondary").css("display","")};c(".gr-nav-menu-item").focus(function(b){c(b.currentTarget).closest(".gr-subnav__group--primary").find(".gr-subnav__group--secondary").css("display",
"flex")});c(".gr-nav-menu-item-no-sub").focus(function(a){b()});c(document).click(function(){b()});c(".gr-subnav__group--secondary .gr-subnav__item").last().keydown(function(a){9==a.keyCode&&b()})})});
/* ******** */
