'use strict';mix_d("AmazonLuxuryWidgetCards__lux-media-single-asset-mobile:lux-media-single-asset-mobile__inwDPEY7",["exports","tslib","@c/scoped-dom","@c/dom"],function(u,v,r,w){var q=r&&"object"===typeof r&&"default"in r?r:{"default":r},x={videoControls:"_lux-media-single-asset-mobile_style_videoControls__1P4z_",playPauseBtn:"_lux-media-single-asset-mobile_style_playPauseBtn__3ccTh",muteBtn:"_lux-media-single-asset-mobile_style_muteBtn__1_yRB",muteSlot:"_lux-media-single-asset-mobile_style_muteSlot__-o5fG",
hidden:"_lux-media-single-asset-mobile_style_hidden__1m-ey"},y={videoPlayer:"_lux-media-single-asset-mobile_style_videoPlayer__21Pas",video:"_lux-media-single-asset-mobile_style_video__AXynd",posterFallback:"_lux-media-single-asset-mobile_style_posterFallback__2PL4k",hidden:"_lux-media-single-asset-mobile_style_hidden__2NzYy"},z=function(d){var a=w.unscope(d)||d;"undefined"===typeof IntersectionObserver?a.play().catch(function(){}):(new IntersectionObserver(function(b){b.forEach(function(c){c.isIntersecting?
a.play().catch(function(){}):a.pause()})},{threshold:.5})).observe(a)},A=function(d,a,b){for(var c=function(){for(var g=0;g<d.length;g++){var e=d[g];e.classList.remove(a);(e=e.querySelector("button"))&&e.setAttribute("aria-expanded","false")}},f=function(g){var e=d[g],k=e.querySelector("button");if(!k)return"continue";k.addEventListener("click",function(p){p.stopPropagation();p=e.classList.contains(a);c();p||(e.classList.add(a),k.setAttribute("aria-expanded","true"),requestAnimationFrame(function(){var l=
e.querySelector('[id^="hotspot-tooltip-"]');if(l&&l.style){l.style.left="50%";l.style.transform="translateX(-50%)";l.style.bottom="40px";l.style.top="auto";var m=e.offsetParent;if(m){m=m.getBoundingClientRect();var n=l.getBoundingClientRect();if(n.width||n.height){if(n.left<m.left){var t=m.left-n.left;l.style.transform="translateX(calc(-50% + "+t+"px))"}else n.right>m.right&&(t=n.right-m.right,l.style.transform="translateX(calc(-50% - "+t+"px))");n.top<m.top&&(l.style.bottom="auto",l.style.top="40px",
n=l.getBoundingClientRect());n.bottom>m.bottom&&(t=e.getBoundingClientRect(),m=m.bottom-n.height-t.top,l.style.bottom="auto",l.style.top=m+"px")}}}}))})},h=0;h<d.length;h++)f(h);b.addEventListener("click",function(g){g=g.target;for(var e=0;e<d.length;e++)if(d[e].contains(g))return;c()});b.addEventListener("keydown",function(g){"Escape"===g.key&&c()})},B=function(d,a){var b=d.querySelector("video"),c=d.querySelector("."+a.playPauseBtn);d=d.querySelector("."+a.muteBtn);if(b&&c){var f=c.querySelector('[data-icon="pause"]'),
h=c.querySelector('[data-icon="play"]');c.addEventListener("click",function(k){k.preventDefault();k.stopPropagation();b.paused?(void b.play(),f&&f.classList.remove(a.hidden),h&&h.classList.add(a.hidden)):(b.pause(),f&&f.classList.add(a.hidden),h&&h.classList.remove(a.hidden))})}if(b&&d){var g=d.querySelector('[data-icon="mute"]'),e=d.querySelector('[data-icon="unmute"]');d.addEventListener("click",function(k){k.preventDefault();k.stopPropagation();b.muted=!b.muted;g&&g.classList.toggle(a.hidden,!b.muted);
e&&e.classList.toggle(a.hidden,b.muted)})}},C={quot:'"',amp:"&",lt:"<",gt:">",apos:"'",nbsp:"\u00a0",copy:"\u00a9",reg:"\u00ae",trade:"\u2122",hellip:"\u2026",mdash:"\u2014",ndash:"\u2013",lsquo:"\u2018",rsquo:"\u2019",ldquo:"\u201c",rdquo:"\u201d"},D=/&(#\d+|#[xX][0-9a-fA-F]+|[A-Za-z][A-Za-z0-9]*);/g,E=function(d){return d.replace(D,function(a,b){if("#"===b.charAt(0)){b="x"===b.charAt(1)||"X"===b.charAt(1)?parseInt(b.slice(2),16):parseInt(b.slice(1),10);try{return String.fromCodePoint(b)}catch(c){return a}}b=
C[b];return void 0!==b?b:a})},F={fast:Infinity,moderate:720,slow:0},G=function(d){d=d.quality;return void 0===d||null===d?!0:"number"===typeof d&&Number.isFinite(d)&&0<d},H=function(d){return d.filter(function(a){return a&&"string"===typeof a.src&&0<a.src.length}).filter(G).slice().sort(function(a,b){var c,f;return(null!==(c=b.quality)&&void 0!==c?c:Infinity)-(null!==(f=a.quality)&&void 0!==f?f:Infinity)})},I=function(){function d(a,b,c){void 0===c&&(c={});this.index=-1;this.observer=null;this.isVisible=
this.destroyed=!1;this.errorCleanup=null;this.cleanups=[];this.root=a;this.playerStyle=b.player||{};this.controlsStyle=b.controls||{};this.onEnded=c.onEnded;this.onExhausted=c.onExhausted;this.media=(this.video=a.querySelector("video"))?w.unscope(this.video)||this.video:null;this.poster=a.querySelector("img");if(!(b=c.sources)){var f=a.getAttribute("data-sources");if(f){f=E(f);try{var h=JSON.parse(f);b=Array.isArray(h)?h:[]}catch(p){b=[]}}else b=[]}this.sources=H(b);a=a.getAttribute("data-autoplay");
this.autoplay=void 0!==c.autoplay?c.autoplay:"false"===a?!1:"immediate"===a||"true"===a?!0:"viewport";if(this.video&&0!==this.sources.length){this.wireControls();c=this.applySource;a=this.sources;try{var g=(h="undefined"!==typeof navigator?navigator:void 0)&&(h.connection||h.mozConnection||h.webkitConnection);var e=g?"number"===typeof g.downlink&&0<g.downlink||!0===g.saveData:!1}catch(p){e=!1}if(e)b:if(e=(e="undefined"!==typeof navigator?navigator:void 0)&&(e.connection||e.mozConnection||e.webkitConnection),
e=!e||"number"!==typeof e.downlink||0>=e.downlink||!0===e.saveData?"slow":5<=e.downlink?"fast":1.5<=e.downlink?"moderate":"slow",0===a.length)var k=-1;else{e=F[e];for(g=0;g<a.length;g++)if((null!==(k=a[g].quality)&&void 0!==k?k:Infinity)<=e){k=g;break b}k=a.length-1}else k=0===a.length?-1:Math.floor((a.length-1)/2);c.call(this,k);this.setupAutoplay()}else this.degradeToPosterOrHide()}d.prototype.applySource=function(a){var b=this;if(this.video&&this.media)if(0>a||a>=this.sources.length)this.degradeToPosterOrHide();
else{this.index=a;this.media.src=this.sources[a].src;this.errorCleanup&&this.errorCleanup();var c=this.media,f=function(){return b.handleError()};c.addEventListener("error",f,{once:!0});this.errorCleanup=function(){return c.removeEventListener("error",f)};"function"===typeof this.media.load&&this.media.load()}};d.prototype.handleError=function(){if(!this.destroyed)if(this.index+1<this.sources.length)this.applySource(this.index+1),(!0===this.autoplay||this.isVisible)&&this.play();else if(this.degradeToPosterOrHide(),
this.onExhausted)this.onExhausted()};d.prototype.degradeToPosterOrHide=function(){this.observer&&(this.observer.disconnect(),this.observer=null);this.pause();var a=this.playerStyle.hidden;this.video&&a&&this.video.classList.add(a);var b=this.controlsStyle.videoControls?this.root.querySelector("."+this.controlsStyle.videoControls):null;b&&a&&b.classList.add(a);this.poster&&a?(this.poster.classList.remove(a),this.poster.setAttribute("aria-hidden","false")):!this.poster&&a&&this.root.classList.add(a)};
d.prototype.hidePoster=function(){var a=this.playerStyle.hidden;this.poster&&a&&this.poster.classList.add(a)};d.prototype.wireControls=function(){var a=this;if(this.video){var b=this.query(this.controlsStyle.playPauseBtn),c=this.query(this.controlsStyle.muteBtn);if(b){var f=function(l){l.preventDefault();l.stopPropagation();a.media&&a.media.paused?a.play():a.pause()};b.addEventListener("click",f);this.cleanups.push(function(){return b.removeEventListener("click",f)});var h=function(){return a.syncPlayPauseUI(b,
!0)},g=function(){return a.syncPlayPauseUI(b,!1)};this.video.addEventListener("play",h);this.video.addEventListener("pause",g);this.cleanups.push(function(){return a.video&&a.video.removeEventListener("play",h)});this.cleanups.push(function(){return a.video&&a.video.removeEventListener("pause",g)});this.syncPlayPauseUI(b,this.media?!this.media.paused:!1)}if(c){var e=function(l){l.preventDefault();l.stopPropagation();a.media&&(a.media.muted=!a.media.muted,a.syncMuteUI(c,a.media.muted))};c.addEventListener("click",
e);this.cleanups.push(function(){return c.removeEventListener("click",e)});this.syncMuteUI(c,this.media?this.media.muted:!0)}if(this.onEnded&&this.video){var k=function(){return a.onEnded&&a.onEnded()};this.video.addEventListener("ended",k);this.cleanups.push(function(){return a.video&&a.video.removeEventListener("ended",k)})}if(this.poster&&this.video){var p=function(){return a.hidePoster()};this.video.addEventListener("playing",p);this.cleanups.push(function(){return a.video&&a.video.removeEventListener("playing",
p)})}}};d.prototype.setupAutoplay=function(){var a=this;this.media&&!1!==this.autoplay&&!this.prefersReducedMotion()&&(!0===this.autoplay?this.play():"undefined"===typeof IntersectionObserver?this.play():(this.observer=new IntersectionObserver(function(b){b.forEach(function(c){(a.isVisible=c.isIntersecting)?a.play():a.pause()})},{threshold:.5}),this.observer.observe(this.media)))};d.prototype.prefersReducedMotion=function(){try{return"function"===typeof matchMedia&&matchMedia("(prefers-reduced-motion: reduce)").matches}catch(a){return!1}};
d.prototype.syncPlayPauseUI=function(a,b){var c=this.controlsStyle.hidden,f=a.querySelector('[data-icon="pause"]'),h=a.querySelector('[data-icon="play"]');f&&c&&f.classList.toggle(c,!b);h&&c&&h.classList.toggle(c,b);a.setAttribute("aria-label",b?"Pause video":"Play video");a.setAttribute("aria-pressed",b?"true":"false")};d.prototype.syncMuteUI=function(a,b){var c=this.controlsStyle.hidden,f=a.querySelector('[data-icon="mute"]'),h=a.querySelector('[data-icon="unmute"]');f&&c&&f.classList.toggle(c,
!b);h&&c&&h.classList.toggle(c,b);a.setAttribute("aria-label",b?"Unmute video":"Mute video");a.setAttribute("aria-pressed",b?"true":"false")};d.prototype.query=function(a){return a?this.root.querySelector("."+a):null};d.prototype.play=function(){if(this.media&&!this.destroyed){var a=this.media.play();a&&"function"===typeof a.catch&&a.catch(function(){})}};d.prototype.pause=function(){this.media&&!this.destroyed&&this.media.pause()};d.prototype.reset=function(){this.media&&!this.destroyed&&(this.media.pause(),
this.media.currentTime=0)};d.prototype.destroy=function(){this.media&&this.media.pause();this.destroyed=!0;this.observer&&(this.observer.disconnect(),this.observer=null);this.errorCleanup&&(this.errorCleanup(),this.errorCleanup=null);for(;0<this.cleanups.length;){var a=this.cleanups.pop();a&&a()}};return d}(),J=function(d,a,b){void 0===b&&(b={});var c=a.player&&a.player.videoPlayer,f=[];(c?d.querySelectorAll("."+c):d.querySelectorAll("[data-sources]")).forEach(function(h){f.push(new I(h,a,b))});return f};
u._operationNames=[];u.card=function(){return v.__awaiter(void 0,void 0,void 0,function(){var d,a;return v.__generator(this,function(b){b=d=q["default"].cardRoot.getElementsByClassName("_lux-media-single-asset-mobile_style_hotspot__1bUSi");for(var c=0;c<b.length;c++){var f=b[c],h=f.getAttribute("data-x"),g=f.getAttribute("data-y");h&&(f.style.left=h+"%");g&&(f.style.top=g+"%")}A(d,"_lux-media-single-asset-mobile_style_active__3AIh_",q["default"].cardRoot);if(q["default"].cardRoot.querySelector("[data-sources]"))return J(q["default"].cardRoot,
{player:y,controls:x}),[2];B(q["default"].cardRoot,x);(a=q["default"].cardRoot.querySelector("video"))&&z(a);return[2]})})}});
