'use strict';mix_d("PrimeAcquisitionCXCards__slash-prime-choose-plan-desktop-card:slash-prime-choose-plan-desktop-card__ugrPQ6b7",["exports","tslib","@c/scoped-dom","@c/aui-untrusted-ajax","@c/logger"],function(y,h,B,C,D){function x(e){return e&&"object"===typeof e&&"default"in e?e:{"default":e}}function z(e,a){return h.__awaiter(this,void 0,void 0,function(){var c;return h.__generator(this,function(d){try{return c={accepts:"application/json",contentType:"application/json;charset=UTF-8",additionalHeaders:E({})},
[2,F["default"].post(a,c,e).then(function(b){(b=b.responseBody.payload.requestSuccess)||t["default"].log("Request the customer name ajax failed","ERROR");return b}).catch(function(b){t["default"].log("An error occurred while publishing metrics",b);return!1})]}catch(b){t["default"].log("Request the customer name ajax failed with the error:"+b,"ERROR")}return[2,!1]})})}function E(e){var a=(a=A["default"].cardRoot.querySelector("meta[name='anti-csrftoken-a2z']"))?a.getAttribute("content"):"";e["anti-csrftoken-a2z"]=
a;return e}var A=x(B),F=x(C),t=x(D),v;(v||(v={})).Count="Count";var G=function(){function e(a){this.endpoint=a.endpoint}e.prototype.publishImpressionMetric=function(a,c,d){var b=v.Count;c=this.getStandardEventData(a,c,d);null===c?t["default"].log("Event data is null and it indicates the DOM associated to the class isn't available","WARN"):this.publishMetric("Impression",1,b,c,a,this.endpoint)};e.prototype.publishButtonClickMetric=function(a,c){var d=this,b=v.Count,g=this.getStandardEventData(a,c);
null===g?t["default"].log("Event data is null and it indicates the DOM associated to the class isn't available","WARN"):(c=document.querySelectorAll(".".concat(a," button")),0===c.length?t["default"].log("No buttons found for the given class","WARN"):c.forEach(function(k){k.addEventListener("click",function(){d.publishMetric("ButtonClick",1,b,g,a,d.endpoint)})}))};e.prototype.publishSpecificButtonClickMetric=function(a,c,d,b,g){var k=this,n=v.Count,l=this.getStandardEventData(a,b,g);null===l?t["default"].log("Event data is null and it indicates the DOM associated to the class isn't available",
"WARN"):(b=document.querySelector('[class*="'.concat(c,'"], [id*="').concat(c,'"]')))?b.addEventListener("click",function(){k.publishMetric(d,1,n,l,a,k.endpoint)}):t["default"].log("Button with selector ".concat(c," not found"),"WARN")};e.prototype.publishCustomMetric=function(a,c,d,b){b=this.extractDimensionsForAdditionalEventData(b);b=Object.fromEntries(b);z({metricName:c,metricValue:d,metricUnit:v.Count,dimensions:b,location:a},this.endpoint)};e.prototype.publishMetric=function(a,c,d,b,g,k){b=
this.extractDimensions(b);b=Object.fromEntries(b);z({metricName:a,metricValue:c,metricUnit:d,dimensions:b,location:g},k)};e.prototype.getStandardEventData=function(a,c,d){return(d=document.querySelector('[class^="'.concat(a,'"], [id^="').concat(a,'"]'))||document.querySelector('div[data-csa-c-painter="'.concat(d,'"]')))?(a={cardName:d.getAttribute("data-csa-c-painter")||a,widgetId:d.getAttribute("data-csa-c-widget-id")||"",pageId:d.getAttribute("data-csa-c-page-id")||"",deviceType:d.getAttribute("data-csa-c-device-type")||
""},h.__assign(h.__assign({},a),c)):null};e.prototype.extractDimensions=function(a){var c,d=new Map;try{for(var b=h.__values(Object.entries(a)),g=b.next();!g.done;g=b.next()){var k=h.__read(g.value,2),n=k[0],l=k[1];"string"!==typeof l&&"number"!==typeof l||""===l.toString()||d.set(n,l.toString())}}catch(u){var p={error:u}}finally{try{g&&!g.done&&(c=b.return)&&c.call(b)}finally{if(p)throw p.error;}}return d};e.prototype.extractDimensionsForAdditionalEventData=function(a){var c,d=new Map;try{for(var b=
h.__values(Object.entries(a)),g=b.next();!g.done;g=b.next()){var k=h.__read(g.value,2),n=k[0],l=k[1];"string"!==typeof l&&"number"!==typeof l||""===l.toString()||d.set(n,l.toString())}}catch(u){var p={error:u}}finally{try{g&&!g.done&&(c=b.return)&&c.call(b)}finally{if(p)throw p.error;}}return d};return e}(),w=function(){function e(){this._state=null}e.getInstance=function(){e.instance||(e.instance=new e);return e.instance};e.prototype.extractMetadata=function(a){var c,d,b,g,k,n,l,p,u,m;a=(a.querySelector("[data-csa-c-metadata-map]")||
a).getAttribute("data-csa-c-metadata-map");var f={};if(a)try{var q=JSON.parse(a),r=q.metadataMap?JSON.parse(q.metadataMap):{},H=h.__assign({offerType:null!==(c=r.offerType)&&void 0!==c?c:"NONE",benefitRestrictionType:null!==(d=r.benefitRestrictionType)&&void 0!==d?d:"NONE",offerSegment:null!==(b=r.offerSegment)&&void 0!==b?b:"NONE",feeType:null!==(g=r.feeType)&&void 0!==g?g:"NONE",benefitTier:null!==(k=r.benefitTier)&&void 0!==k?k:"NONE",variantId:null!==(n=r.variantId)&&void 0!==n?n:"NONE",offerListingId:null!==
(l=r.offerListingId)&&void 0!==l?l:"NONE",experimentTagMetadata:null!==(p=r.experimentTagMetadata)&&void 0!==p?p:"NONE"},r.multiplan?{multiplan:r.multiplan}:{}),I={marketingContentCreativeId:null!==(u=q.marketingContentCreativeId)&&void 0!==u?u:"NONE",acquisitionDevice:null!==(m=q.acquisitionDevice)&&void 0!==m?m:"NONE"};f=h.__assign(h.__assign({},H),I)}catch(J){t["default"].log("Error parsing analyticalMetadataMap:"+J,"ERROR")}return f};e.prototype.initialize=function(a,c,d,b){var g=this.extractMetadata(d);
d=d.querySelector("[data-csa-c-widget-id]")||d;var k=d.getAttribute("data-csa-c-widget-id")||"";this._state={publisher:new G({endpoint:a}),cardName:c,csaAttributes:g,painterId:b,widgetId:k,pageId:d.getAttribute("data-csa-c-page-id")||"",deviceType:d.getAttribute("data-csa-c-device-type")||""}};e.prototype.publishImpression=function(a){var c=this.getState();c.publisher.publishImpressionMetric(c.cardName,h.__assign(h.__assign({},c.csaAttributes),a),c.painterId)};e.prototype.publishMetricWithCoreDimensions=
function(a,c){void 0===c&&(c=1);var d=this.getState();d.publisher.publishCustomMetric(d.cardName,a,c,{widgetId:d.widgetId,acquisitionDevice:d.csaAttributes.acquisitionDevice||""})};e.prototype.publishMetricWithVariantOnly=function(a,c){void 0===c&&(c=1);var d=this.getState();d.publisher.publishCustomMetric(d.cardName,a,c,{widgetId:d.widgetId,variantId:this.getVariantId()})};e.prototype.getVariantId=function(){return this.getState().csaAttributes.variantId||""};e.prototype.publishSpecificButtonClickWithMultiplan=
function(a,c,d){var b=this.getState();b.csaAttributes.multiplan&&(a=d.querySelector("#"+a))&&a.addEventListener("click",function(){b.publisher.publishCustomMetric(b.cardName,c,1,h.__assign({cardName:b.cardName,widgetId:b.widgetId,pageId:b.pageId,deviceType:b.deviceType},b.csaAttributes))})};e.prototype.publishButtonClick=function(a){var c=this.getState();c.publisher.publishButtonClickMetric(c.cardName,h.__assign(h.__assign({},c.csaAttributes),a))};e.prototype.publishSpecificButtonClick=function(a,
c,d){var b=this.getState();b.publisher.publishSpecificButtonClickMetric(b.cardName,a,c,h.__assign(h.__assign({},b.csaAttributes),d),b.painterId)};e.prototype.publishSpecificButtonClickWithVariantOnly=function(a,c,d){var b=this,g=this.getState();d.querySelectorAll("#"+a).forEach(function(k){k.addEventListener("click",function(){g.publisher.publishCustomMetric(g.cardName,c,1,{widgetId:g.widgetId,variantId:b.getVariantId()})})})};e.prototype.publishCustomMetric=function(a,c,d){var b=this.getState();
b.publisher.publishCustomMetric(b.cardName,a,c,h.__assign(h.__assign({cardName:b.cardName},b.csaAttributes),d))};e.prototype.getState=function(){if(!this._state)throw Error("MetricsService must be initialized before use");return this._state};return e}().getInstance(),K=["campaignId","clientId","ingressId","offerToken"],L=function(e){return h.__awaiter(void 0,void 0,void 0,function(){var a,c,d,b,g,k,n,l,p;return h.__generator(this,function(u){a=e.cardRoot;c=e.cardId;d=e.painterId;w.initialize("/prime-ajax/acquisition/metrics",
c,a,d);w.publishImpression();w.publishMetricWithCoreDimensions("Impression");w.publishSpecificButtonClick("choosePlanCTAButton","signupMetric");b=a.querySelectorAll('input[type="radio"]');g=a.querySelector("#choose-plan-subtext");k=a.querySelector("#choosePlanCTAButton-announce");n=a.querySelector("form");l=function(m){var f=a.querySelector("#offer-description-"+m);g&&f&&(g.innerHTML="",Array.from(f.childNodes).forEach(function(q){g.appendChild(q.cloneNode(!0))}));f=a.querySelector("#hiddenTextcta"+
m);k.textContent=f.value;m=a.querySelector("#wlpData"+m);p(JSON.parse(m.value))};p=function(m){n.action=m.formActionURL;Object.entries(m).filter(function(f){f=h.__read(f,2);var q=f[0];f[1];return K.includes(q)}).map(function(f){f=h.__read(f,2);var q=f[1];return[a.querySelector('form input[name="'+f[0]+'"]'),q]}).filter(function(f){f=h.__read(f,2);var q=f[0];f[1];return null!==q}).forEach(function(f){f=h.__read(f,2);return f[0].value=f[1]})};b.forEach(function(m){m.addEventListener("change",function(f){f=
f.target;f.checked&&(f=f.id.replace("RadioButtonInput",""),l(f))})});return[2]})})};y._operationNames=[];y.card=function(){return h.__awaiter(void 0,void 0,void 0,function(){return h.__generator(this,function(e){return[2,L({cardRoot:A["default"].cardRoot,cardId:"slash-prime-choose-plan-desktop-card",painterId:"slash-prime-choose-plan-desktop-card"})]})})}});
